### ISSUE TITLE
Write SoX playback handler

### ISSUE THREAD

**Issue by renekliment** [alexa-pi/AlexaPi#106]
This should:
- solve audio problems:
    - fix #63 (hopefully)
    - sound problems on legacy kernel Orange Pi (@renekliment confirms)
    - CHIP with internal sound card (maybe, who knows)
- enable us to support OpenWRT
- save space and maybe (just maybe) be a little faster

The current VLC handler isn't great and the whole thing needs a refactor regarding `.stop()` and resuming radio playback and stuff (#117), but that doesn't block this. 
Also some methods could be reused, so it might not be a bad idea to move them to the base handler, but we'll see how that turns out. Namely `queued_play`, `blocking_play` and `process_queue`.

@illperipherals showed interest in doing this, but it is currently free to take.

Random links: https://github.com/rabitt/pysox

**Comment by enclarify** [comment]
I have this feature mostly working. I need to cleanup the code and add the sox packages to all platforms this weekend and then will submit a PR for review

**Comment by renekliment** [comment]
@enclarify Dope!

**Comment by ImEmJay** [comment]
+reneliment Sounds reasonable. It should work better than the vlc handler but including it fast as a optional feature can get a broader test-base faster.

**Comment by enclarify** [comment]
@renekliment That makes sense given that I don't have access to all supported platforms for testing

**Comment by renekliment** [comment]
Fixed by #140.
