### ISSUE TITLE
Adding Hyperion support for playback/record status

### ISSUE THREAD

**Issue by penfold42** [alexa-pi/AlexaPi#113]
I want to use Hyperion (ambient lighting) to display the playback record status.

It's a really simple json request over tcp to set the led colours.

Should I do this as a separate platform or could we do this for all platforms ?

**Comment by renekliment** [comment]
Hey. Currently, the best approach is indeed a new _device_platform_. You can inherit from whatever existing platform you like (if you want to keep its function) and just add your code.

**Comment by renekliment** [comment]
@penfold42 Do you have any further questions / help requests / code to share?

**Comment by ImEmJay** [comment]
@renekliment Because I also like to have Hyperion support and your 'device_platform' makes it really easy I already started implementing it.

@penfold42 I think I'm ready to push a first into a public branch in my repo within the next days. Would you like to do some testing then?

**Comment by penfold42** [comment]
Yep - I have to get it working again tho which is why inhavemt done anything yet.

I was going to NOT use Hyperion-remote by rather use the json interface over tcp to set the colour.
We should expose the actual json string in the config file too

**Comment by ImEmJay** [comment]
You can already set the colors independent for each state. Also you can choose between static color or 'knight rider' effect for all states. Additionaly you can override each state t use flashing notifications as you can see in the video when alexa is triggering the playback state.
I think not all effects would look good as notification and it's a bit tricky cause they all have different parameters. But im looking to integrate/customize more of the default effects. Still i would avoid to just pass the full args string as a config option.

**Comment by renekliment** [comment]
This was fixed in `dev` by #127.
