### ISSUE TITLE
amazon has an error and not accepting my authorization

### ISSUE THREAD

**Issue by baum1234** [alexa-pi/AlexaPi#124]
I just installed everything on my Raspberry Pi.
After the setup I went to http://192.168.2.2:5050 and accepted the authorization to my account. After pressing "Ok", I get this message (in German):

> Tut uns leid!
Beim Bearbeiten Ihres Auftrags ist ein Fehler aufgetreten. Wir arbeiten bereits daran und haben das Problem in Kürze gelöst.

That just means that there is an error and that they are working on it.
When I visit https://www.amazon.de/ap/adam or https://www.amazon.com/ap/adam there is no entry.

Had anyone the same problem and found a solutoin

**Comment by melvinhertz** [comment]
I had this problem. I had to create a new device and call it my_device and then it worked. I think I found that solution on the amazon alexa github page somewhere.

**Comment by melvinhertz** [comment]
Also, make sure your return url code is exactly right in your security profile.

**Comment by hackerseraph** [comment]
my_device resolved this for me as well. thanks team.

**Comment by baum1234** [comment]
silly question, how do I start AlexPi after I ran the setup once?

**Comment by dgonano** [comment]
`sudo service AlexaPi Start` or `src/main.py -d` for debugging

**Comment by renekliment** [comment]
@baum1234 If this is resolved, please close the issue. Thank you.
