### ISSUE TITLE
Issue with audio output front_center.wav

### ISSUE THREAD

**Issue by datafaust** [alexa-pi/AlexaPi#139]
Ran into some audio issues after installing. Appreciate any help!

**Output of the [audio debugging script](https://github.com/alexa-pi/AlexaPi/wiki/Audio-setup-&-debugging#audio-debugging-script).**

http://www.alsa-project.org/db/?f=1dad84c07847476c65f18e561ba4bf9e8f331366

**Your OS (including version) where you are running AlexaPi:**
```
I'm running CHIP o.s. debian kernel 4.3
Kernel release:    4.3.0-ntc
Operating System:  GNU/Linux
```

**Your hardware platform and model you are running on:**
CHIP

**Description of problem:**
 I followed installation directions without issue, under root and configured with the "root" issues as instructed. I wanted to test audio so I've been playing:

`aplay /usr/share/sounds/alsa/Front_Center.wav`

to test audio ouput but I get a pause, then 

`: Signed 16 bit Little Endian, Rate 48000 Hz, Mono`

and then a response aplay:

`pcm_write:1939: write error: Input/output error`

aplay -l shows no devices it seems:
```
**** List of PLAYBACK Hardware Devices ****
card 0: sun4icodec [sun4i-codec], device 0: CDC PCM Codec-0 []
  Subdevices: 1/1
  Subdevice #0: subdevice #0

however arecord -l shows my mic working properly:
card 1: Device [DYNEX USB MIC Device], device 0: USB Audio [USB Audio]
  Subdevices: 0/1
  Subdevice #0: subdevice #0
```

**Expected:**
 I expected playback of the deafult .wav file to test audio ouput and then followup with mic test.

**additional notes**
I've received the following errors when checking for the Alexapi service. It's active but then i get the following:
```
Jan 07 20:16:42 chip systemd[1]: Started Alexa client for all your devices.
Jan 07 22:15:32 chip python[186]: [00ee2030] alsa audio output error: canno...ry
Jan 07 22:15:32 chip python[186]: [00ee2030] core audio output error: Audio...ed
Jan 07 22:15:32 chip python[186]: [00ee2030] core audio output error: The a...d:
Jan 07 22:15:32 chip python[186]: No such file or directory.
Jan 07 22:15:32 chip python[186]: [00ee2030] core audio output error: modul...al
Jan 07 22:15:32 chip python[186]: [b4612d40] core decoder error: failed to ...ut

Warning: Unit file changed on disk, 'systemctl daemon-reload' recommended.
Hint: Some lines were ellipsized, use -l to show in full.
```

When debugging interactive I got the following:
```
Checking Internet Connection...
Connection OK
Play_Audio Request for: /opt/AlexaPi/src/resources/hello.mp3
Player State: State.Opening
Player State: State.Playing
[b1900500] alsa audio output error: cannot open ALSA device "plughw:1": No such file or directory
[b1900500] core audio output error: Audio output failed
[b1900500] core audio output error: The audio device "plughw:1" could not be used:
No such file or directory.
[b1900500] core audio output error: module not functional
[b4612cb0] core decoder error: failed to create audio output
Player State: State.Ended
```

**Comment by renekliment** [comment]
Hm, your audio is messed up. Did you configure ALSA yourself?

Try setting the `input_device` to `usb` in `config.yaml`.

Also, if you don't have other stuff on the CHIP I suggest you do a clean install of the latest system. I believe they have an OS with kernel at least 4.4 for it.

**Comment by enclarify** [comment]
Based on what you pasted I think your playback device should be `plughw:0` and your input device `plughw:1`. You can test your devices like this:

`aplay -f S16_LE -D plughw:0 /usr/share/sounds/alsa/Front_Center.wav`

and 

`arecord -f S16_LE -D plughw:1 /tmp/test.wav`

**Comment by enclarify** [comment]
Additionally `src/scripts/inc/chip.sh` should likely be changed to:

`config_set 'output_device' 'plughw:0'`

**Comment by datafaust** [comment]
@enclarify , it seems that the file, src/scripts/inc/chip.sh does not exist, which seems to point to messup @renekliment  is mentioning. Seems like I can't output any sound at all I continue to get the input writeout error. I'm going to try a fresh install, on another chip I have or a reboot of the software on this chip and see what happens.

**Comment by datafaust** [comment]
So I tried all the suggestions and no luck, short of re flashing which I might try. Quick question before I do though. I've been using the GUI through VNC, so I decided to test the rca connection again (was working 2 days ago) on my tv under the suspicion that there might be an issue withoutput overall and I can't get an image out to my tv through the 3.5mm jack anymore. Do you guys know how this might be related to this issue? Is there a general messup with files that not allowing any output through the jack?

**Comment by enclarify** [comment]
@datafaust Unfortunately, I don't know much about using the 3.5mm jack because I have an audio amplifier that's fed from the U14 header and operate it headless. One of my CHIPs is older and has not been flashed yet. I tested it prior to my first reply and it functions as expected. On all my CHIPs the buildin audio device is 0 and the USB mic that I am using is 1. The NTC forums are great for specific CHIP info. You might have more luck with your question there

**Comment by renekliment** [comment]
@datafaust Damn, don't delete comments. 
Anyways, you should first get audio in your OS working (aplay, arecord). Closing for now as it doesn't concern AlexaPi. Feel free to come back and reopen / file a new issue when needed.
