### ISSUE TITLE
400 Bad Request on http://localhost:5050 and Local IP?

### ISSUE THREAD

**Issue by AR019** [alexa-pi/AlexaPi#172]
**Your OS (including version) where you are running AlexaPi:**
```
Ubuntu (MATE)
```

**Your hardware platform and model you are running on:**
```
Pine64+ 2GB
```

**Python release (`python2 --version`):**
```
Python 2.7.12
```

**Description of problem:**
```
Getting 400 Bad Request when attempting to connect to http://localhost:5050 or http://The_Local_IP:5050 from amazon.com. Page also states that URLs are not whitelisted for application even though they are.
```

**Expected:**
```
Amazon Authorization Page
```

**Problem-relevant `config.yaml` entries:**
```
N/A or (Believed to be) Not applicable for this issue.
```

**Steps to reproduce:**

1. cd /opt/AlexaPi/src/scripts && sudo ./setup.sh
2. Go through setup, then "Ready goto" is presented along with the URLs 
3. Try to connect to http://localhost:5050 or the Local IP with :5050

**Additional info:**
```
Connection to Pine64 is bridged from a laptop running Kali Linux via Ethernet (Could that be an issue?)
URLs are whitelisted, ran setup with following setup options:
For OS: debian (Ubuntu MATE)
For system/platform option: other
Autostart: Yes
Restart upon crashing: Yes
Airplay Compatibility: Yes

UPDATE: Tried connection without a bridge, same error even after fixing the Local IP to the newest one.
```

**Comment by frisco82** [comment]
Are you sure you added that url to your app in amazon developer panel?
https://github.com/alexa-pi/AlexaPi/wiki/Installation

You need to add localhost:5050 and also the local ip you use to connect from your pc.

**Comment by renekliment** [comment]
Make sure you add the url exactly as you enter it in your browser. Note also you need both URLs -`Allowed Origins` and `Allowed Return URLs` with the `/code`.

People often think they do it right, but they don't.

Also, there could be a problem with failed install - similar issue lately. That will be resolved in 2 weeks by releasing a new version. If you can't make it work, just wait for the new version.

**Comment by EmerickH** [comment]
@AR019 you don't replied so I suppose you solved your issue...
Please re-open the issue if you still have the problem.

Emerick
