### ISSUE TITLE
Amazon Music no longer working?

### ISSUE THREAD

**Issue by cgioconda** [alexa-pi/AlexaPi#191]
Is Amazon Music no longer approved for use with AlexaPi? I set up a new install on my RPi2, created a new device profile in the Amazon Dev console, and seemingly appear to be approved to use Amazon Music in my new security profile, yet AlexaPi still tells me "Amazon Music is not supported for this device".

On another website (Martian Watches) in their faq, they state: "– I have setup my music service, but got a response on my watch saying “Amazon music is not supported for this device”. Yes, at the time Amazon Alexa is only authorized to play music through Amazon Echo and Dot devices that are tethered by Bluetooth to a compatible music sound system."

**Comment by cgioconda** [comment]
It appears I am still pending - closing this case.

**Comment by renekliment** [comment]
See #90 for details.
