### ISSUE TITLE
Amazon Music?

### ISSUE THREAD

**Issue by Fireful0** [alexa-pi/AlexaPi#204]
Hello!
Just found this project, got it installed correctly, and love it!
Had a question though:
I have seen people who have been able to listen to Amazon Music songs from theirs, and wanted to do the same thing.
Is it still possible?

**Comment by renekliment** [comment]
https://github.com/alexa-pi/AlexaPi/wiki/Q&A-(FAQ)#does-alexapi-support-amazon-music
