### ISSUE TITLE
Error message at start:Access denied 

### ISSUE THREAD

**Issue by Muscatnuss** [alexa-pi/AlexaPi#205]
When I try to start AVS with 'systemctl start AlexaPi.service' I get the following error message:
Failed to start AlexaPi.service: Access denied.
I tried the trouble shooting methods of the instructions but nothing worked. I deleted the whole program and reinstalled it three times but i was getting the same results every time.
When i scanned the programm with 'sudo journalctl -u AlexaPi.service' I couldn't see any errors.
I use a Rasperry Pi 3 with Raspbian Jessie wich has python 3
I'm new to Raspberry Pi so please be gentle.

**Comment by maso27** [comment]
You need to put _sudo_ in front of the command.
So `sudo systemctl start AlexaPi.service`
And you can make it start at boot with `sudo systemctl enable AlexaPi.service`

**Comment by Muscatnuss** [comment]
Thanks for helping me! Now it works.

**Comment by renekliment** [comment]
Added into https://github.com/alexa-pi/AlexaPi/wiki/Installation#3-post-installation-steps 
Thanks for reporting and sorry we missed this in the first place.
