### ISSUE TITLE
Choppy audio

### ISSUE THREAD

**Issue by flyboy320** [alexa-pi/AlexaPi#218]
I have Alexa installed and working on my Raspberry Pi 3, but the audio is choppy. I have set up PA to run in system wide mode, installed sox and also VLC, but it's still choppy. Is there anything else I can try (this happens on both the HDMI and 3.5 audio out)?

**Comment by JamesZEMOURI** [comment]
in /etc/opt/Alexapi/config.yaml
i change :

```
playback_handler: "vlc"
```
to :
``` 
playback_handler: "sox"
```
worked for me 😄

**Comment by flyboy320** [comment]
I tried that but when I set it to sox there is no audio.

**Comment by flyboy320** [comment]
I tried a fresh install of Raspbian with Pixel buy with the same result. Before I install VLC, the audio is very bad to the point there is audio only every five seconds or so. once I install VLC, the audio is much improved, but it still occasionally skips/stutters .

Also I once again did as JamesZEMOURI suggested and changed vlc to sox, but when I do that there is no audio at all.

**Comment by JoePotchen** [comment]
I believe I'm having the same issue you're having. I've changed over to sox and I'm getting no audio at all so I opened it up in debug and I'm getting a "missing filename" sox error.

`2017-04-20 17:57:52 DEBUG: Setting up playback handler: SoxHandler
2017-04-20 17:57:52 INFO: Checking Internet Connection ...
2017-04-20 17:57:52 DEBUG: Starting new HTTPS connection (1): api.amazon.com
2017-04-20 17:57:53 DEBUG: https://api.amazon.com:443 "GET /auth/o2/token HTTP/1.1" 404 29
2017-04-20 17:57:53 INFO: Connection OK
2017-04-20 17:57:53 INFO: AVS token: Requesting a new one
2017-04-20 17:57:53 DEBUG: Starting new HTTPS connection (1): api.amazon.com
2017-04-20 17:57:53 DEBUG: https://api.amazon.com:443 "POST /auth/o2/token HTTP/1.1" 200 962
2017-04-20 17:57:53 INFO: AVS token: Obtained successfully
2017-04-20 17:57:53 DEBUG: Stopping audio play
2017-04-20 17:57:53 DEBUG: Stopped play. No SoX process to stop
2017-04-20 17:57:53 DEBUG: Playing audio: /opt/AlexaPi/src/resources/hello.mp3
2017-04-20 17:57:53 DEBUG: Started play. sox -q /opt/AlexaPi/src/resources/hello.mp3 -t pulse vol -6 dB pad 0 0
2017-04-20 17:57:53 DEBUG: Error attempting play. sox FAIL sox: missing filename`

**Comment by flyboy320** [comment]
Yes, I get the same error "Error attempting play. sox FAIL sox: missing filename'

**Comment by WeCreate180** [comment]
Erm. Ok, I'm probably going to get this wrong. But do you actually have sox installed?

**Comment by renekliment** [comment]
> DEBUG: Error attempting play. sox FAIL sox: missing filename

If I remember correctly, I got this when  I was using a wrong `output_device` ... looking at the code ... do you guys have a space characted in your `output_device`? There might be a bug in the code. 

Try tweaking the setting and get back here with your setting. Thanks.

**Comment by flyboy320** [comment]
I was chatting at the AlexaPi/Lobby on gitter and had some great help from @Romain_LE_BARS_twitter. Were were unable to get sox to work, but he had me use v1.4 of AlexaPi instead of the newest one, and with VLC as the handler, the choppy, stuttering, skipping audio is gone.

Not sure if that helps, but anyone else with choppy audio could try v1.4
`cd /opt/AlexaPi/

sudo git checkout v1.4'

**Comment by JoePotchen** [comment]
I'll give that a go when I get home tonight I guess, haha. Thanks!

**Comment by JoePotchen** [comment]
Well, I went back to 1.4 and I'm still getting choppy audio using VLC :/. I'll keep playing around with it to see what I can get.

**Comment by flyboy320** [comment]
I guess sox still doesn't work for you on v1.4 (it didn't for me)?

**Comment by icodemachine** [comment]
Sox works for me after installing through pip install sox (make sure you use a version older than the current one 1.2.8). But the problem is: It gets stuck for a several minutes after playback

Started play. sox -q /tmp/AlexaPi-runtime-ptdqM3/KnowledgePrompt.4afac634-2959-4211-8cc4-6cacfae32026_200714149.mp3 -t alsa default vol -6 dB pad 0 0

**Comment by flyboy320** [comment]
How do you install an earlier version of sox?

**Comment by renekliment** [comment]
> Sox works for me after installing through pip install sox (make sure you use a version older than the current one 1.2.8). But the problem is: It gets stuck for a several minutes after playback

This doesn't make sense at all. AlexaPi doesn't use the sox python wrapper and the sox binary is not contained in the release package.

**Comment by icodemachine** [comment]
Sorry my bad. I got mixed up, I assumed soxhandler would be using the wrapper. Anyways for people having the problem with no file error, just do apt-get install sox.

But the playback getting stuck error still persists.

**Comment by flyboy320** [comment]
>  Anyways for people having the problem with no file error, just do apt-get install sox

Tried that, but problem still there.

`playback_handler: "sox"`

This gives no sound at all, but

`playback_handler: "vlc"`

This gives sound and on v1.4 AlexaPi it's smooth playback, but on current/newest AlexaPi it's verey choppy for me.

**Comment by EmerickH** [comment]
I've solved this problem.
In your config:
```
  playback_handler: "sox"
  output: "pulseaudio"
  output_device: "default"
```
(it's not pulse but **pulseaudio**, I found it in sox's documentation)
And do:
`sudo apt-get install libsox-fmt-pulse`

It's working for me!

**Comment by flyboy320** [comment]
I tried the config you suggested EmerickH, but I still get an error when trying to use sox. It works for the most part using vlc instead, just the occasional audio choppiness.

**Comment by EmerickH** [comment]
@flyboy320 can you copy/paste the log?

Emerick

**Comment by flyboy320** [comment]
@EmerickH  here you go

2017-06-01 14:27:29 INFO: AVS token: Requesting a new one
2017-06-01 14:27:29 DEBUG: Starting new HTTPS connection (1): api.amazon.com
2017-06-01 14:27:30 DEBUG: https://api.amazon.com:443 "POST /auth/o2/token HTTP/1.1" 200 978
2017-06-01 14:27:30 INFO: AVS token: Obtained successfully
2017-06-01 14:27:30 DEBUG: Stopping audio play
2017-06-01 14:27:30 DEBUG: Stopped play. No SoX process to stop
2017-06-01 14:27:30 DEBUG: Playing audio: /opt/AlexaPi/src/resources/hello.mp3
2017-06-01 14:27:30 DEBUG: Started play. sox -q /opt/AlexaPi/src/resources/hello.mp3 -t pulseaudio default vol -6 dB pad 0 0
2017-06-01 14:27:30 DEBUG: Error attempting play. sox FAIL formats: no handler for given file type `pulseaudio'

**Comment by EmerickH** [comment]
@flyboy320 are you shure to have pulse?
```
sudo apt-get update
sudo apt-get install pulseaudio libsox-fmt-pulse
```

Emerick

**Comment by EmerickH** [comment]
@flyboy320 without reply I think it's solved
This issue has bee reported a lot of time so I group them all here: https://github.com/alexa-pi/AlexaPi/issues/242
