### ISSUE TITLE
Consistent Issues with Audio , even with pulse audio setup

### ISSUE THREAD

**Issue by sunildm4u** [alexa-pi/AlexaPi#221]
**Output of the [audio debugging script](https://github.com/alexa-pi/AlexaPi/wiki/Audio-setup-&-debugging#audio-debugging-script).**

**Your OS (including version) where you are running AlexaPi:**
```
Raspbian
```

**Your hardware platform and model you are running on:**
```
Raspberry Pi Model 3b
```

**Python release (`python2 --version`):**
```

```

**Description of problem:**
```
It never starts on reboot nor manually. Audio is choppy even after moving to SOX. Followed every step in detail as in document. 

After solving permission issue by chmod for AlexaPI User, Final error was realted to authorization on cookie. 
Sorry Couldnt capture the details
```

**Expected:**
```

```

**Problem-relevant `config.yaml` entries:**
```

```

**Steps to reproduce:**

1. 
2. 
3. 

**Traceback (if applicable):**
```

```

**Additional info:**
```

```

**Comment by EmerickH** [comment]
Incomplete issue please re-open the issue and provide more details if you still have the problem
