### ISSUE TITLE
Debug Input device

### ISSUE THREAD

**Issue by teddylambert** [alexa-pi/AlexaPi#237]
Thank you for reporting an issue with **AlexaPi**.

Make sure you are running the latest version of **AlexaPi**, and look through [issues](https://github.com/alexa-pi/AlexaPi/issues?utf8=%E2%9C%93&q=is%3Aissue) before submitting.

Check out our [Wiki](https://github.com/alexa-pi/AlexaPi/wiki/), and make sure to look at [Debugging](https://github.com/alexa-pi/AlexaPi/wiki/Debugging/), and [Audio debugging](https://github.com/alexa-pi/AlexaPi/wiki/Audio-setup-&-debugging) in particular before filing an issue.

In order to help troubleshooting, be sure to include the following information:

**Output of the [audio debugging script](https://github.com/alexa-pi/AlexaPi/wiki/Audio-setup-&-debugging#audio-debugging-script).**
![screen shot 2017-05-19 at 7 41 38 pm](https://cloud.githubusercontent.com/assets/13473151/26271433/4e656d02-3ccb-11e7-8301-aa50800211d3.png)

**Your OS (including version) where you are running AlexaPi:**
```
Linux Raspbian 3-02-2017 release
```

**Your hardware platform and model you are running on:**
```
Raspberry Pi 2B with JBL speaker and Playstation eye camera/mic
```

**Python release (`python2 --version`):**
```
2.7.9
```

**Description of problem:**
```
I ran the debug, and followed the instructions to copy the plughw into the "input-device" field. Yet I still don't have audio, and when I re-run the debug (with the new config) it gives the same error. Any ideas?
```

**Expected:**
```

```

**Problem-relevant `config.yaml` entries:**
```

```

**Steps to reproduce:**

1. 
2. 
3. 

**Traceback (if applicable):**
```

```

**Additional info:**
```

```

**Comment by renekliment** [comment]
Do what the script tells you. Set the `input_device` to one from the list - probably the last one.

**Comment by teddylambert** [comment]
That's what I originally did (I pasted the last one), and doing so threw out the error above. Maybe I'm copy/pasting wrong?

**Comment by teddylambert** [comment]
Update:
When I tried switching ``` input_device:``` to one of the other values (I used ```surround40:CARD=CameraB409241,DEV=0``` as a test value), when running ```/opt/AlexaPi/src/main.py -d``` I still get this-
![screen shot 2017-05-20 at 4 50 57 pm](https://cloud.githubusercontent.com/assets/13473151/26279544/8dc83ffe-3d7c-11e7-89ee-813684a55abb.png)

This is my ```config.yaml```, is there anything that I'm missing here?-
![screen shot 2017-05-20 at 4 52 36 pm](https://cloud.githubusercontent.com/assets/13473151/26279570/e05c8040-3d7c-11e7-88d8-2c91a6fda5ef.png)

**Comment by probststefan** [comment]
Try it with: `input_device: "plughw:CARD=CameraB409241,DEV=0"`

That worked for me

**Comment by harimau99** [comment]
But i thought the solution was either way around.. But changing to respective listener hardware plugin. or input devices..
