### ISSUE TITLE
Security Profile ID

### ISSUE THREAD

**Issue by wyattHarrell** [alexa-pi/AlexaPi#238]
How can I add my Security Profile ID?

Mistakenly skipped over the Security Profile ID when prompted. I entered in everything else, Client ID, Client Secret, etc. Which file is all of this information in as there is no creds.py?

**Comment by renekliment** [comment]
https://github.com/alexa-pi/AlexaPi/wiki/Configuration-file

You then have to run `auth.py` to obtain a token from Amazon.
