### ISSUE TITLE
Alexa not working with Alsa on RaspberryPi

### ISSUE THREAD

**Issue by EmerickH** [alexa-pi/AlexaPi#242]
# Problem
In the actual **master branch** of **AlexaPi**, Alsa is not working as input driver.

# Example of not working `config.yaml`
```
sound:
  input_device: "plughw:CARD=C110,DEV=0"
  allow_unlisted_input_device: false
  playback_handler: "vlc"
  output: "alsa"
```
# How to solve?

Use **pulseaudio** instead of **alsa**.

## With VLC:

Do` sudo apt-get install pulseaudio`
and in your config, put:
```
  input_device: "pulse"
  allow_unlisted_input_device: false
  playback_handler: "vlc"
  output: "pulse"
  output_device: "default"
```

## With SoX:

Do `sudo apt-get install pulseaudio libsox-fmt-pulse`
and in your config, put:
```
  input_device: "pulse"
  allow_unlisted_input_device: false
  playback_handler: "sox"
  output: "pulseaudio"
  output_device: "default"
```

Emerick

**Comment by ezar** [comment]
+1

**Comment by EmerickH** [comment]
Hello @ezar,
You have two solution:

1. you can use pulseaudio instead of alsa.
Install it:
`sudo apt-get install pulseaudio`
and put in your config file:
`input_device: "pulse"`
2. install [the last developement version](https://github.com/alexa-pi/AlexaPi/tree/dev)
`git clone -b dev https://github.com/alexa-pi/AlexaPi.git`
PyAudio has been replaced by Pyalsaaudio, it should works better (if you try this solution can you say me if it's working?)


Emerick

**Comment by ezar** [comment]
Nothing.. I test using webcam mic, an external usb mic, ... 
Magic Word "Alexa" is not detected.

I try:
1. Pulse audio.
2. PyAudio. Latest development version.

Can you share your config file?

**Comment by EmerickH** [comment]
Hello,
strange...
My config is:
```
  input_device: "pulse"
  allow_unlisted_input_device: false
  playback_handler: "sox"
  output: "pulseaudio"
  output_device: "default"
```
I'm using Sox, but it doesn't change anything with input device
(if you want to use Sox, do `sudo apt-get install pulseaudio libsox-fmt-pulse`)

Maybe pulseaudio is not correctly configured... I don't know how to configure it with pacmd but there's packages to do it easier.

- If you have a graphical interface, install `pavucontrol`:
`sudo apt-get install pavucontrol`
and launch it with `pavucontrol` command.
You can now check if the input devices are correctly configured.

- If you don't have one, try `pamixer`
Try:
`sudo apt-get install pamixer`
if it's not working, install it manually:
```
git clone https://github.com/cdemoulins/pamixer.git
cd pamixer
make
./pamixer
```

Emerick

**Comment by ezar** [comment]
Hi,
I use your config... doesn't works!
Using "pavucontrol" I verify that mic is detected... seems a problem with AlexaPi because arecord works correctly.
:(

**Comment by ezar** [comment]
Do you user trigger "Alexa" or use button?
Regards,

**Comment by EmerickH** [comment]
Hello,
I'm using **pocketshpinx** ("Alexa" trigger).
Can you copy/paste your log?
See [here](https://github.com/alexa-pi/AlexaPi/wiki/Debugging#debug-mode) in the **Debug mode** category to start in debug mode to see the complete log

Emerick

**Comment by ezar** [comment]
2017-06-13 21:41:38 DEBUG: Initialising Magic Mirror platorm
INFO: pocketsphinx.c(152): Parsed model-specific feature parameters from /usr/local/lib/python2.7/dist-packages/pocketsphinx/model/en-us/feat.params
Current configuration:
[NAME]                  [DEFLT]         [VALUE]
-agc                    none            none
-agcthresh              2.0             2.000000e+00
-allphone                               
-allphone_ci            no              no
-alpha                  0.97            9.700000e-01
-ascale                 20.0            2.000000e+01
-aw                     1               1
-backtrace              no              no
-beam                   1e-48           1.000000e-48
-bestpath               yes             yes
-bestpathlw             9.5             9.500000e+00
-ceplen                 13              13
-cmn                    live            batch
-cmninit                40,3,-1         41.00,-5.29,-0.12,5.09,2.48,-4.07,-1.37,-1.78,-5.08,-2.05,-6.45,-1.42,1.17-compallsen             no              no
-debug                                  0
-dict                                   /usr/local/lib/python2.7/dist-packages/pocketsphinx/model/cmudict-en-us.dict
-dictcase               no              no
-dither                 no              no
-doublebw               no              no
-ds                     1               1
-fdict                                  
-feat                   1s_c_d_dd       1s_c_d_dd
-featparams                             
-fillprob               1e-8            1.000000e-08
-frate                  100             100
-fsg                                    
-fsgusealtpron          yes             yes
-fsgusefiller           yes             yes
-fwdflat                yes             yes
-fwdflatbeam            1e-64           1.000000e-64
-fwdflatefwid           4               4
-fwdflatlw              8.5             8.500000e+00
-fwdflatsfwin           25              25
-fwdflatwbeam           7e-29           7.000000e-29
-fwdtree                yes             yes
-hmm                                    /usr/local/lib/python2.7/dist-packages/pocketsphinx/model/en-us
-input_endian           little          little
-jsgf                                   
-keyphrase                              alexa
-kws                                    
-kws_delay              10              10
-kws_plp                1e-1            1.000000e-01
-kws_threshold          1               1.000000e-10
-latsize                5000            5000
-lda                                    
-ldadim                 0               0
-lifter                 0               22
-lm                                     
-lmctl                                  
-lmname                                 
-logbase                1.0001          1.000100e+00
-logfn                                  
-logspec                no              no
-lowerf                 133.33334       1.300000e+02
-lpbeam                 1e-40           1.000000e-40
-lponlybeam             7e-29           7.000000e-29
-lw                     6.5             6.500000e+00
-maxhmmpf               30000           30000
-maxwpf                 -1              -1
-mdef                                   
-mean                                   
-mfclogdir                              
-min_endfr              0               0
-mixw                                   
-mixwfloor              0.0000001       1.000000e-07
-mllr                                   
-mmap                   yes             yes
-ncep                   13              13
-nfft                   512             512
-nfilt                  40              25
-nwpen                  1.0             1.000000e+00
-pbeam                  1e-48           1.000000e-48
-pip                    1.0             1.000000e+00
-pl_beam                1e-10           1.000000e-10
-pl_pbeam               1e-10           1.000000e-10
-pl_pip                 1.0             1.000000e+00
-pl_weight              3.0             3.000000e+00
-pl_window              5               5
-rawlogdir                              
-remove_dc              no              no
-remove_noise           yes             yes
-remove_silence         yes             yes
-round_filters          yes             yes
-samprate               16000           1.600000e+04
-seed                   -1              -1
-sendump                                
-senlogdir                              
-senmgau                                
-silprob                0.005           5.000000e-03
-smoothspec             no              no
-svspec                                 0-12/13-25/26-38
-tmat                                   
-tmatfloor              0.0001          1.000000e-04
-topn                   4               4
-topn_beam              0               0
-toprule                                
-transform              legacy          dct
-unit_area              yes             yes
-upperf                 6855.4976       6.800000e+03
-uw                     1.0             1.000000e+00
-vad_postspeech         50              50
-vad_prespeech          20              20
-vad_startspeech        10              10
-vad_threshold          2.0             2.000000e+00
-var                                    
-varfloor               0.0001          1.000000e-04
-varnorm                no              no
-verbose                no              no
-warp_params                            
-warp_type              inverse_linear  inverse_linear
-wbeam                  7e-29           7.000000e-29
-wip                    0.65            6.500000e-01
-wlen                   0.025625        2.562500e-02

INFO: feat.c(715): Initializing feature stream to type: '1s_c_d_dd', ceplen=13, CMN='batch', VARNORM='no', AGC='none'
INFO: acmod.c(166): Using subvector specification 0-12/13-25/26-38
INFO: mdef.c(518): Reading model definition: /usr/local/lib/python2.7/dist-packages/pocketsphinx/model/en-us/mdef
INFO: mdef.c(531): Found byte-order mark BMDF, assuming this is a binary mdef file
INFO: bin_mdef.c(336): Reading binary model definition: /usr/local/lib/python2.7/dist-packages/pocketsphinx/model/en-us/mdef
INFO: bin_mdef.c(516): 42 CI-phone, 137053 CD-phone, 3 emitstate/phone, 126 CI-sen, 5126 Sen, 29324 Sen-Seq
INFO: tmat.c(149): Reading HMM transition probability matrices: /usr/local/lib/python2.7/dist-packages/pocketsphinx/model/en-us/transition_matrices
INFO: acmod.c(117): Attempting to use PTM computation module
INFO: ms_gauden.c(127): Reading mixture gaussian parameter: /usr/local/lib/python2.7/dist-packages/pocketsphinx/model/en-us/means
INFO: ms_gauden.c(242): 42 codebook, 3 feature, size: 
INFO: ms_gauden.c(244):  128x13
INFO: ms_gauden.c(244):  128x13
INFO: ms_gauden.c(244):  128x13
INFO: ms_gauden.c(127): Reading mixture gaussian parameter: /usr/local/lib/python2.7/dist-packages/pocketsphinx/model/en-us/variances
INFO: ms_gauden.c(242): 42 codebook, 3 feature, size: 
INFO: ms_gauden.c(244):  128x13
INFO: ms_gauden.c(244):  128x13
INFO: ms_gauden.c(244):  128x13
INFO: ms_gauden.c(304): 222 variance values floored
INFO: ptm_mgau.c(476): Loading senones from dump file /usr/local/lib/python2.7/dist-packages/pocketsphinx/model/en-us/sendump
INFO: ptm_mgau.c(500): BEGIN FILE FORMAT DESCRIPTION
INFO: ptm_mgau.c(563): Rows: 128, Columns: 5126
INFO: ptm_mgau.c(595): Using memory-mapped I/O for senones
INFO: ptm_mgau.c(838): Maximum top-N: 4
INFO: phone_loop_search.c(114): State beam -225 Phone exit beam -225 Insertion penalty 0
INFO: dict.c(320): Allocating 138824 * 20 bytes (2711 KiB) for word entries
INFO: dict.c(333): Reading main dictionary: /usr/local/lib/python2.7/dist-packages/pocketsphinx/model/cmudict-en-us.dict
INFO: dict.c(213): Dictionary size 134723, allocated 1016 KiB for strings, 1679 KiB for phones
INFO: dict.c(336): 134723 words read
INFO: dict.c(358): Reading filler dictionary: /usr/local/lib/python2.7/dist-packages/pocketsphinx/model/en-us/noisedict
INFO: dict.c(213): Dictionary size 134728, allocated 0 KiB for strings, 0 KiB for phones
INFO: dict.c(361): 5 words read
INFO: dict2pid.c(396): Building PID tables for dictionaryINFO: dict2pid.c(406): Allocating 42^3 * 2 bytes (144 KiB) for word-initial triphones
INFO: dict2pid.c(132): Allocated 21336 bytes (20 KiB) for word-final triphones
INFO: dict2pid.c(196): Allocated 21336 bytes (20 KiB) for single-phone word triphones
INFO: kws_search.c(406): KWS(beam: -1080, plp: -23, default threshold -225, delay 10)
2017-06-13 21:41:40 DEBUG: Setting up playback handler: SoxHandler
2017-06-13 21:41:40 DEBUG: Setting up Magic Mirror platform
2017-06-13 21:41:40 INFO: Magic Mirror HTTP Server - :5055
2017-06-13 21:41:40 INFO: Checking Internet Connection ...
2017-06-13 21:41:40 DEBUG: Starting new HTTPS connection (1): api.amazon.com
2017-06-13 21:41:41 DEBUG: https://api.amazon.com:443 "GET /auth/o2/token HTTP/1.1" 404 29
2017-06-13 21:41:41 INFO: Connection OK
2017-06-13 21:41:41 INFO: AVS token: Requesting a new one2017-06-13 21:41:41 DEBUG: Starting new HTTPS connection (1): api.amazon.com
2017-06-13 21:41:42 DEBUG: https://api.amazon.com:443 "POST /auth/o2/token HTTP/1.1" 200 977
2017-06-13 21:41:42 INFO: AVS token: Obtained successfully
2017-06-13 21:41:42 DEBUG: Starting Magic Mirror platform HTTP Server
2017-06-13 21:41:42 DEBUG: Starting Magic Mirror heartbeat with 5 second interval
2017-06-13 21:41:42 DEBUG: Sending MM Heatbeat
2017-06-13 21:41:42 DEBUG: Response: {"status":"success"}2017-06-13 21:41:42 DEBUG: Stopping audio play
2017-06-13 21:41:43 DEBUG: Stopped play. No SoX process to stop
2017-06-13 21:41:43 DEBUG: Indicate Stop Playing
2017-06-13 21:41:43 DEBUG: Calling URL: http://localhost:8080/alexapi?action=AVSSTATUS&status=idle
2017-06-13 21:41:43 DEBUG: Response: {"status":"success"}2017-06-13 21:41:43 DEBUG: Playing audio: /opt/AlexaPi/src/resources/hello.mp3
2017-06-13 21:41:43 DEBUG: Started play. sox -q /opt/AlexaPi/src/resources/hello.mp3 -t pulseaudio default vol -6 dB pad 0 0
2017-06-13 21:41:43 DEBUG: Indicate Start Playing
2017-06-13 21:41:43 DEBUG: Calling URL: http://localhost:8080/alexapi?action=AVSSTATUS&status=playback
2017-06-13 21:41:43 DEBUG: Response: {"status":"success"}2017-06-13 21:41:45 DEBUG: Finished play. 
2017-06-13 21:41:45 DEBUG: Indicate Stop Playing
2017-06-13 21:41:45 DEBUG: Calling URL: http://localhost:8080/alexapi?action=AVSSTATUS&status=idle
2017-06-13 21:41:46 DEBUG: Response: {"status":"success"}2017-06-13 21:41:46 DEBUG: Indicating Success
2017-06-13 21:41:46 DEBUG: Calling URL: http://localhost:8080/alexapi?action=AVSSTATUS&status=success
2017-06-13 21:41:46 DEBUG: Response: {"status":"success"}2017-06-13 21:41:47 DEBUG: Sending MM Heatbeat
2017-06-13 21:41:47 DEBUG: Response: {"status":"success"}^C2017-06-13 21:41:48 DEBUG: Cleaning up Magic Mirror platform
2017-06-13 21:41:48 DEBUG: Cleaning up playback handler
2017-06-13 21:41:48 DEBUG: Stopped play. [Errno 3] No such process
2017-06-13 21:41:48 DEBUG: Indicate Stop Playing
2017-06-13 21:41:48 DEBUG: Calling URL: http://localhost:8080/alexapi?action=AVSSTATUS&status=idle
2017-06-13 21:41:49 DEBUG: Response: {"status":"success"}INFO: cmn_live.c(88): Update from < 41.00 -5.29 -0.12  5.09  2.48 -4.07 -1.37 -1.78 -5.08 -2.05 -6.45 -1.42  1.17 >
INFO: cmn_live.c(105): Update to   < 44.82 -11.86 -7.02 -2.72 -7.96  0.93  3.32 -5.41 -9.14  0.32 -1.12 -0.98  2.14 >

**Comment by ezar** [comment]
# See https://github.com/alexa-pi/AlexaPi/wiki/Audio-setup-&-debugging
# to get a better idea of how to set things in here

# Level of log output
# default: INFO
# set to DEBUG for verbose logging
logging: INFO

sound:
  # Name of your ALSA microphone/soundcard in arecord -L
  #input_device: "default"
  input_device: "pulse"
  # This is here if none of the listed device: "magicmirror"
  # This is an override that is normally not needed and is a last resort.
  allow_unlisted_input_device: false

  #playback_handler: "vlc"
  playback_handler: "sox"

  # you can go here with alsa, pulse or others
  # keep blank for the best audio output selected by the underlying code
  #output: "alsa"
  output: "pulseaudio"
  # output device: "magicmirror"
  # currently supports ALSA only
  output_device: "default"

  # if left empty, won't be passed to the underlying library / command if it supports it
  # if it doesn't 100% will be used
  default_volume: 80

  # Means the same as above, but is used for media (playing music for example)
  # Leave blank to use the same setting as for speech content
  media_output:
  media_output_device:
  media_default_volume:

  # Some device: "magicmirror"
  # value is the number of seconds of silence to pad the beginning and end of the audio. Only
  # the sox handler supports this configuration option.
  playback_padding: 0

# Amazon Alexa settings
### removed

# See https://github.com/alexa-pi/AlexaPi/wiki/Triggers for the description of these options
triggers:
  platform:
    enabled: true
    voice_confirm: false

    # one of: oneshot-vad, continuous, continuous-vad
    event_type: "oneshot-vad"

    # only for "continuous" event_types
    long_press:
      # system command to run after pressing the button for _duration_ number of seconds
      # empty to disable
      command: ""

      # duration in seconds
      duration: 10

      # CURRENTLY DISABLED
      # optional audio file to play before executing the command
      # you might wanna use full path to make sure AlexaPi finds it
      # you can use {resources_path} for the path to the AlexaPi "resources" directory
      audio_file: ""


  pocketsphinx:
    enabled: true
    voice_confirm: true

    phrase: "alexa"
    threshold: 1e-10

# Commands to run before and after an interaction begins. Leave empty to disable.
event_commands:

  # Example used to lower shairport-sync volume during interaction with alexa
  #     startup: "amixer set shairportvolume 100%"
  #     pre_interaction: "amixer set shairportvolume 10%-""
  #     post_interaction: "amixer set shairportvolume 10%+""
  # Note this assumes you have redirected shairport-syncs audio to a seperate softdevice
  # with control "shairportvolume". Example asound.conf avalible in the scripts folder

  # Command to run at the start of AlexaPi
  startup: ""

  # Command to run after a trigger is detected but before an interaction begins
  pre_interaction: ""

  # Command to run after the interaction has completed
  post_interaction: ""

  # Command to run during a clean shutdown of AlexaPi
  shutdown: ""

platform:
  # Name of your platform, e.g. raspberrypi, orangepi, desktop
  device: "magicmirror"

platforms:
  # common config for all platforms (if they support the options)
  # can be overriden in the the respective platform sections
  common:

  chip:
    # GPIO Pin with button connected
    button: XIO-P1
    # GPIO Pin for the playback/activity light
    plb_light: XIO-P3
    # GPIO Pin for the recording light
    rec_light: XIO-P5

  raspberrypi:
    # GPIO Pin with button connected
    button: 18
    # GPIO Pin for the playback/activity light
    plb_light: 24
    # GPIO Pin for the recording light
    rec_light: 25

  orangepi:
    # GPIO Pin with button connected
    button: 20
    # GPIO Pin for the playback/activity light
    plb_light: 9
    # GPIO Pin for the recording light
    rec_light: 8

  desktop:
    min_seconds_to_record: 3

  dummy:

  magicmirror:
    # Magic Mirror - github.com/MichMich/MagicMirror
    # Integrates with MMM-AlexaPi module (github.com/dgonano/MMM-AlexaPi) to display listening, playback, etc status
    # Hostname of the AlexaPi HTTP server, leave empty for any name
    hostname: ""
    # Port the ALexaPi HTTTP server binds to
    port: 5055
    # Hostname of the Magic Mirror
    mm_hostname: "localhost"
    # Port of the Magic Mirror
    mm_port: "8080"
    # How ofter the Hearbeat fires in seconds
    hb_timer: 5

  hyperion:
    # Hostname of the Hyperion node's JSON server
    hyperion_json_host: "127.0.0.1"
    # Port of the Hyperion node's JSON server
    hyperion_json_port: 19444
    # Visual status as static 'color' or 'effect'
    # Overridden by 'hyperion_flash_state_xxx'
    hyperion_mode: "effect"
    # Running speed when visualizing as 'effect'
    hyperion_effect_speed: 1
    hyperion_priority: 1
    color_playback: [80, 213, 35]
    color_processing: [35,169,213]
    color_recording: [168, 35, 213]
    flash_duration: 500
    flash_frequency: 8
    # Use Strobe effect instead of default effect or static color
    flash_state_playback: true
    flash_state_processing: false
    flash_state_recording: false
    # Visualize playback state
    indicate_playback: true
    #Also print json request/response when in debug mode
    verbose: false

  serial:
    port: "/dev/ttyACM0"
    baudrate: 9600
    messages:
      trigger: ""
      playback_start: "g"
      playback_end: "x"
      recording_start: ""
      recording_end: ""
      processing_start: ""
      processing_end: ""
      failure: ""
      success: ""

**Comment by ezar** [comment]
Config.yaml
https://pastebin.com/Sk0Gz8VL

**Comment by ezar** [comment]
I install python 3, updated pip libs, ... nothing!
Alexa trigger doesn't work. Can I trigger using URL . Seems that using magic mirror integration I can... how?

**Comment by EmerickH** [comment]
Hello,
You don't precise that you use `magicmirror`...
It's written on your config:
```
# output device: "magicmirror"
# currently supports ALSA only
```

So your config must be:
```
sound:
  # Name of your ALSA microphone/soundcard in arecord -L
  input_device: "default"
  # This is here if none of the listed device: "magicmirror"
  # This is an override that is normally not needed and is a last resort.
  allow_unlisted_input_device: false
 
  playback_handler: "vlc"
or
  playback_handler: "sox"
 
  # you can go here with alsa, pulse or others
  # keep blank for the best audio output selected by the underlying code
  output: "alsa"
  # output device: "magicmirror"
  # currently supports ALSA only
  output_device: "default"
or try
  output_device: "magicmirror"
```

Emerick

**Comment by ezar** [comment]
Nothimg! Doesn't works. I try your config but Alexa magic word don't wake the system.

I hear hello using Alsa and Pulseaudio. 

The problem it's wake up. Every configuration doesn't works. I reinstall Jessie Lite many times.

Regards

**Comment by EmerickH** [comment]
@ezar what do you use like input device in your config?
You can list them with `arecord -L`
(uses only `plughw:` devices)

Emerick

**Comment by ezar** [comment]
`default
    Playback/recording through the PulseAudio sound server
null
    Discard all samples (playback) or generate zero samples (capture)
pulse
    PulseAudio Sound Server
sysdefault:CARD=Device
    USB PnP Sound Device, USB Audio
    Default Audio Device
front:CARD=Device,DEV=0
    USB PnP Sound Device, USB Audio
    Front speakers
surround21:CARD=Device,DEV=0
    USB PnP Sound Device, USB Audio
    2.1 Surround output to Front and Subwoofer speakers
surround40:CARD=Device,DEV=0
    USB PnP Sound Device, USB Audio
    4.0 Surround output to Front and Rear speakers
surround41:CARD=Device,DEV=0
    USB PnP Sound Device, USB Audio
    4.1 Surround output to Front, Rear and Subwoofer speakers
surround50:CARD=Device,DEV=0
    USB PnP Sound Device, USB Audio
    5.0 Surround output to Front, Center and Rear speakers
surround51:CARD=Device,DEV=0
    USB PnP Sound Device, USB Audio
    5.1 Surround output to Front, Center, Rear and Subwoofer speakers
surround71:CARD=Device,DEV=0
    USB PnP Sound Device, USB Audio
    7.1 Surround output to Front, Center, Side, Rear and Woofer speakers
iec958:CARD=Device,DEV=0
    USB PnP Sound Device, USB Audio
    IEC958 (S/PDIF) Digital Audio Output
dmix:CARD=Device,DEV=0
    USB PnP Sound Device, USB Audio
    Direct sample mixing device
dsnoop:CARD=Device,DEV=0
    USB PnP Sound Device, USB Audio
    Direct sample snooping device
hw:CARD=Device,DEV=0
    USB PnP Sound Device, USB Audio
    Direct hardware device without any conversions
plughw:CARD=Device,DEV=0
    USB PnP Sound Device, USB Audio
    Hardware device with all software conversions`

**Comment by EmerickH** [comment]
@ezar try to install the last dev version: https://github.com/alexa-pi/AlexaPi/wiki/Q&A-(FAQ)#how-to-try-the-dev-branch

**Comment by ezar** [comment]
Updated to dev branch.

Config.yaml
```
sound:
  # Name of your microphone device in PortAudio
  # leave empty for default
  input_device: ""

  #playback_handler: "vlc"
  playback_handler: "sox"

  # you can go here with alsa, pulse or others
  # keep blank for the best audio output selected by the underlying code
  output: "alsa"
  # output device for the audio output specified above,
  # currently supports ALSA only
  output_device: "default"

  # if left empty, won't be passed to the underlying library / command if it supports it
  # if it doesn't 100% will be used
  default_volume: 80

  # Means the same as above, but is used for media (playing music for example)
  # Leave blank to use the same setting as for speech content
  media_output:
  media_output_device:
  media_default_volume:

  # Some device: "magicmirror"
  # value is the number of seconds of silence to pad the beginning and end of the audio. Only
  # the sox handler supports this configuration option.
  playback_padding: 0
```

New logs:
https://pastebin.com/e5fNBJfK

**Comment by EmerickH** [comment]
Ok now try changing your device.
see my reply in your issue https://github.com/alexa-pi/AlexaPi/issues/256#issuecomment-308051900

**Comment by ezar** [comment]
2017-06-15 11:02:37 CRITICAL: Your input_device 'plughw:CARD=Device,DEV=0' is invalid. Use one of the following:
pulse
default

**Comment by ezar** [comment]
Using this seems to works Alexa trigger: https://github.com/dolanmiu/MMM-awesome-alexa/

**Comment by renekliment** [comment]
We use PyAudio now. Closing.
