### ISSUE TITLE
Alexa won't respond because of corrupted record

### ISSUE THREAD

**Issue by lap-tran** [alexa-pi/AlexaPi#245]
I have PS3 eye, Pi2 on Raspbian Jesse Lite. Everything works fine until Alexa needs to respond. She almost never does.

Debug and play recording.wav file, I found the audio stream was corrupted, just random noise and contained an odd number of bytes. That's weird because each frame are 2 bytes.

Further debugged, I saw in most records, there was one time - quite early - alsaaudio.read() returned negative length. From pyalsaaudio documentation, that period is overrun. In that case, the returned buffer is only one byte. When we write that single byte to stream, all subsequent good frames are shifted in a half frame, result in corrupted data.

Solution: ignore overrun period.

**Comment by lap-tran** [comment]
Proposed fix
In src/alexapi/capture.py, change a single line as below (ignore overrun period)

```
	# now do VAD
	while (force_record and force_record[0]()) \
			or (do_VAD and (thresholdSilenceMet is False) and ((time.time() - start) < self.MAX_RECORDING_LENGTH)):
		length, data = inp.read()
		if length > 0:  # ignore overrun period
			yield data

```

**Comment by harimau99** [comment]
Great. Will try your method...

**Comment by harimau99** [comment]
In my side. It didn't workout. Didn't have error just muted.

**Comment by renekliment** [comment]
@lap-tran Hey. Thanks for the debugging. Currently we use PyAudio in the `dev` branch. Can you give it a try and see if the issue persists?

**Comment by lap-tran** [comment]
The dev branch works fine, isn't affected by this bug.

**Comment by harimau99** [comment]
Yep.. its work perfectly.. @renekliment , what was the issue?

**Comment by renekliment** [comment]
I don't know. Linux audio is pure magic. Anyways, the stuff is in `master` now. Closing.
