### ISSUE TITLE
Voice action to trigger local shell script?

### ISSUE THREAD

**Issue by usamitysam** [alexa-pi/AlexaPi#260]
I'm learning here..  I want to give Alexapi an action and have it run a local shell script on the raspberry pi Alexapi unit.  Is this possible?  

This would be helpful to get around the lack of timers, and various other limitations like being unable to do local discovery.    My primary goal is to force a Phillips Hue interface via the command line.

PS - Is there a forum that would be a better place to ask these kinds of question.

**Comment by EmerickH** [comment]
Duplicate as https://github.com/alexa-pi/AlexaPi/issues/216

**Comment by jabulonboaz** [comment]
Have you found a solution? #216 does not offer any real answers
