### ISSUE TITLE
Im trying to force alexapi through usb audio

### ISSUE THREAD

**Issue by JMaker26** [alexa-pi/AlexaPi#270]
Alexa only works through HDMI.

**Comment by EmerickH** [comment]
Please check your device name with `aplay -L` and change your config:
https://github.com/alexa-pi/AlexaPi/wiki/Audio-setup-&-debugging#setting-up-your-devices

Emerick

**Comment by renekliment** [comment]
AlexaPi works fine over USB Audio. You just have set it up in the config.
