### ISSUE TITLE
Alexa does not finish her outputspeech when shouldendsession is set to false

### ISSUE THREAD

**Issue by harithatwork** [alexa-pi/AlexaPi#275]
When I set shouldendsession to false. The response speech was cut off abruptly

**Comment by EmerickH** [comment]
I think it's because of this that `shouldendsession` has been implemented. @renekliment am I wrong?
Why do you want to disable it?

Emerick

**Comment by renekliment** [comment]
I don't know what this is. Closing. Feel free to reopen.
