### ISSUE TITLE
Output over external soundcard

### ISSUE THREAD

**Issue by ThomasKoscheck** [alexa-pi/AlexaPi#281]
Hello together,
I love this project on my Pi. Thanks for that.

To get a better audio quality I want to ask if it is possible to get the audiooutput of alexa through an external usb soundcard. In the setup I can only choose between the audio jack and hdmi.

I want to add alexapi to my home music system and with the audio jack of the pi it is not possible to hear music in good quality.

Best regards
ThomasK.

**Comment by maso27** [comment]
Short answer: yes.

Long answer: yes, and you can also choose to have Alexa's voice play through a separate device from the media (music and whatnot).  Bluetooth devices can also be used.
It's all controlled within _/etc/opt/AlexaPi/config.yaml_.  

Attach the device, use `aplay -L` to list all available devices, and copy the whole line for the device you want to play through into _config.yaml_ as your "output device".

So, for example, if I want to force Alexa to play via my 3.5mm headphone jack, the line in _config.yaml_ reads:
`output_device: "plughw:CARD=ALSA,DEV=0"`
