### ISSUE TITLE
Question about WakeWord

### ISSUE THREAD

**Issue by DJS2017** [alexa-pi/AlexaPi#295]
Dear friend, I am wondering if your github has implemented WakeWord (automatically detected) or is this more like a push a button and talk?

The WakeWord Agent that I am referring to is [here](https://github.com/alexa/alexa-avs-sample-app/tree/master/samples/wakeWordAgent/src).

If this part has been implemented, is it possible to tell me which python program has it, and does it stream onto a buffer or save the audio into a .wav file? Thanks!

**Comment by renekliment** [comment]
https://github.com/alexa-pi/AlexaPi/wiki/Triggers

**Comment by DJS2017** [comment]
Thanks for your reply.


After wake word triggers , does it call capture.silence to record the audio?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
