### ISSUE TITLE
Alexa not booting up

### ISSUE THREAD

**Issue by maciekbaczmanski** [alexa-pi/AlexaPi#298]
Thank you for reporting an issue with **AlexaPi**.

Make sure you are running the latest version of **AlexaPi**, and look through [issues](https://github.com/alexa-pi/AlexaPi/issues?utf8=%E2%9C%93&q=is%3Aissue) before submitting.

Check out our [Wiki](https://github.com/alexa-pi/AlexaPi/wiki/), and make sure to look at [Debugging](https://github.com/alexa-pi/AlexaPi/wiki/Debugging/), and [Audio debugging](https://github.com/alexa-pi/AlexaPi/wiki/Audio-setup-&-debugging) in particular before filing an issue.

In order to help troubleshooting, be sure to include the following information:

**Output of the [audio debugging script](https://github.com/alexa-pi/AlexaPi/wiki/Audio-setup-&-debugging#audio-debugging-script).**

**Your OS (including version) where you are running AlexaPi:**
```
Raspbian (newest version)
```

**Your hardware platform and model you are running on:**
```
Raspberry Pi 3, Model B
```

**Python release (`python2 --version`):**
```

```

**Description of problem:**
```
Alexa doesn't even turn on. After checking service status this is what I get:
pi@raspberrypi:~ $ sudo systemctl status AlexaPi.service
● AlexaPi.service - Alexa client for all your devices
   Loaded: loaded (/usr/lib/systemd/system/AlexaPi.service; enabled)
   Active: failed (Result: exit-code) since Mon 2017-08-14 22:11:07 UTC; 20s ago
     Docs: https://github.com/alexa-pi/AlexaPi/wiki
  Process: 1307 ExecStart=/usr/bin/python /opt/AlexaPi/src/main.py --daemon (code=exited, status=1/FAILURE)
 Main PID: 1307 (code=exited, status=1/FAILURE)

Aug 14 22:11:07 raspberrypi python[1307]: surround50:CARD=VF0770,DEV=0
Aug 14 22:11:07 raspberrypi python[1307]: surround51:CARD=VF0770,DEV=0
Aug 14 22:11:07 raspberrypi python[1307]: surround71:CARD=VF0770,DEV=0
Aug 14 22:11:07 raspberrypi python[1307]: iec958:CARD=VF0770,DEV=0
Aug 14 22:11:07 raspberrypi python[1307]: dmix:CARD=VF0770,DEV=0
Aug 14 22:11:07 raspberrypi python[1307]: dsnoop:CARD=VF0770,DEV=0
Aug 14 22:11:07 raspberrypi python[1307]: hw:CARD=VF0770,DEV=0
Aug 14 22:11:07 raspberrypi python[1307]: plughw:CARD=VF0770,DEV=0
Aug 14 22:11:07 raspberrypi systemd[1]: AlexaPi.service: main process exited, code=exited, status=1/FAILURE
Aug 14 22:11:07 raspberrypi systemd[1]: Unit AlexaPi.service entered failed state.

```

**Expected:**
```

```

**Problem-relevant `config.yaml` entries:**
```

```

**Steps to reproduce:**

1. 
2. 
3. 

**Traceback (if applicable):**
```

```

**Additional info:**
```

```

**Comment by renekliment** [comment]
Misconfigured audio. Anyways, update to version 1.6, that might help. One way or the other, read the whole logs and our docs.
