### ISSUE TITLE
Continuous Integration (CI)

### ISSUE THREAD

**Issue by renekliment** [alexa-pi/AlexaPi#3]
Probably Travis CI? Do you guys have any experience with it? I can give it a shot.

**Comment by renekliment** [comment]
@sammachin I've wanted to register Travis CI for this, but it seems that it needs your permission as the organization owner. It should have sent you an e-mail or something. Could you allow please?

Also, could you add @illperipherals to the organization? 
Thank you.

**Comment by sammachin** [comment]
Done and done!

**Comment by renekliment** [comment]
Cool, thanks. I see however at least the setup of Travis CI as a part of this issue (the tests can go in a different one), therefore I'm keeping this open for now.

**Comment by renekliment** [comment]
Forgot to tag this issue in the commit (damn), so mentioning here and now. 
#16 contains a super basic setup of Travis CI. Keeping this open until we get something more sane and the tests don't fail by default.

**Comment by renekliment** [comment]
Silly me again! #36 contains fixes, so this repo builds successfully by default now. The build pass is mandatory now for new PRs. When we do #21, we'll enable other pylint stuff to check more than just errors and then we can close this.

For tests, there should be a separate issue.
