### ISSUE TITLE
I can't find the device type id

### ISSUE THREAD

**Issue by billcui57** [alexa-pi/AlexaPi#302]
Raspbian
Raspberry Pi 3

I can't find the device type id

 https://developer.amazon.com/avs/home.html#/avs/products/new
 I was provided with the security profile id description,Security Profile ID,Client ID,Client secret,Product ID,Security Profile Name,Security Profile Description, but developer.amazon.com did not show me the device type id, which was a requisite for the setup process. As a matter of fact, it didn't even prompt me to create a device type id at all! I looked through several installation tutorials, and all of them just glides over the fact that a device type id exists without telling me how to create one. Perhaps all the installation tutorials are outdated? Perhaps the amazon website was updated?

**Comment by maso27** [comment]
It looks like you're right--amazon has updated their developer website.
What used to be called "Device Type ID" is now called "Product name".
It's the main name you've given your Alexa project.

Try that and see if it works.

**Comment by Tardog** [comment]
A small correction: The former "Device Type ID" has been renamed to "Product ID", not "Product name".

**Comment by Deranger72** [comment]
a very important correction Tardog thx ;-) - but you both saved my day - thx ;-)

**Comment by inderpartap** [comment]
is it product ID or amazon ID?

**Comment by iguana03** [comment]
not works Product ID neither Amazon ID

**Comment by DjDemonD** [comment]
I just used Product ID from the page titled Alexa Voice Service - Products - Product details - Information - Product ID
Then filled the other fields which are named exactly the same on AlexaPi config as they are on Alexa Voice Service website.
Rebooted Pi and was greeted by Alexa saying "hello". Now just to install the 2mics-hat so I can use it.

**Comment by rtaveras07** [comment]
is the name of your device, after asking by your OS....
