### ISSUE TITLE
Alexa service not starting

### ISSUE THREAD

**Issue by Justarandomman** [alexa-pi/AlexaPi#315]
I was trying to set up my raspberry Pi to run Alexa, and here I am, one step away from completing it and it hits me with this error message. If I had to guess, it's the fact that I'm using a playstation Eye, and yet I heard a lot of people say that it worked fine

 AlexaPi.service - Alexa client for all your devices                            
   Loaded: loaded (/usr/lib/systemd/system/AlexaPi.service; enabled; vendor pres 
   Active: failed (Result: exit-code) since Sun 2017-09-24 14:51:08 UTC; 9min ag 
     Docs: https://github.com/alexa-pi/AlexaPi/wiki                              
  Process: 459 ExecStart=/usr/bin/python /opt/AlexaPi/src/main.py --daemon (code 
 Main PID: 459 (code=exited, status=1/FAILURE)                                   
                                                                                 
Sep 24 14:51:08 raspberrypi python[459]: surround51:CARD=CameraB409241,DEV=0     
Sep 24 14:51:08 raspberrypi python[459]: surround71:CARD=CameraB409241,DEV=0     
Sep 24 14:51:08 raspberrypi python[459]: iec958:CARD=CameraB409241,DEV=0         
Sep 24 14:51:08 raspberrypi python[459]: dmix:CARD=CameraB409241,DEV=0           
Sep 24 14:51:08 raspberrypi python[459]: dsnoop:CARD=CameraB409241,DEV=0         
Sep 24 14:51:08 raspberrypi python[459]: hw:CARD=CameraB409241,DEV=0             
Sep 24 14:51:08 raspberrypi python[459]: plughw:CARD=CameraB409241,DEV=0         
Sep 24 14:51:08 raspberrypi systemd[1]: AlexaPi.service: Main process exited, co 
Sep 24 14:51:08 raspberrypi systemd[1]: AlexaPi.service: Unit entered failed sta 
Sep 24 14:51:08 raspberrypi systemd[1]: AlexaPi.service: Failed with result 'exi

**Comment by renekliment** [comment]
In my experience, Eye on Raspberry Pi sucks d*** without some advanced configuration by someone experienced enough.

Anyways, you need to see the **whole bloody log** ... https://github.com/alexa-pi/AlexaPi/wiki/Debugging#logs ... then you'll find out you don't have audio configured properly. However a new release came out today. Just update and try if the PyAudio works better for you. Cheers.
