### ISSUE TITLE
using alexa-pi to control belkin wemos emulated devices

### ISSUE THREAD

**Issue by moham96** [alexa-pi/AlexaPi#318]
Hi, i'm running alexa-pi on a raspberry pi 3 and trying to add smart home devices, using the fauxmo library [https://bitbucket.org/xoseperez/fauxmoesp](https://bitbucket.org/xoseperez/fauxmoesp) on a nodemcu (esp8266) to emulate belkin wemos, but when i search for devices using alexa app i can't find the device, i don't know if this bug is in alexa-pi or the fauxmo library so i would like to know if anyone was able to get smart home devices in alexa-pi.
Thanks

**Comment by renekliment** [comment]
https://github.com/alexa-pi/AlexaPi/wiki/Q&A-(FAQ)#can-i-discover-my-devices-with-alexapi-like-with-echo
