### ISSUE TITLE
Can you update to the new API?

### ISSUE THREAD

**Issue by Cole128** [alexa-pi/AlexaPi#340]
I think the old API may not be supported by Amazon anymore, and may be causing #331.

**Comment by renekliment** [comment]
Duplicate of #50

**Comment by Cole128** [comment]
Of course, sorry.

**Comment by aussiemax** [comment]
Firstly this is a great project! Combining AlexaPi with Shairport-sync.... Genius!
Do you have a timeline of when you move to the new API?
