### ISSUE TITLE
Error when logging in at localhost:5050

### ISSUE THREAD

**Issue by makeworld-the-better-one** [alexa-pi/AlexaPi#358]
When I run the install script, or run auth_web.py individually, I get the amazon screen, but after clicking okay, I get an error:
![screen shot 2017-12-17 at 2 08 24 pm](https://user-images.githubusercontent.com/25111343/34082825-c762fe4a-e333-11e7-8c28-5ef8df56fcb4.png)

**Comment by HansMees** [comment]
I have the same problem

**Comment by jroza1** [comment]
So then, what is the way forward?  Do we have to go back to the legit Amazon code without the autologin?  
I am getting the same error, but when I go into my console, I do see that my AlexaPi is registered.  Also as I call out to Alexa, she doesn't seem to be doing anything.

**Comment by Cole128** [comment]
I think the only thing to do is wait for the devs to fix it. 🙁

**Comment by Bibelo** [comment]
So I basically lost 3 hours because the dev didn't bother mentionning it on his page.

Thank you dev.

**Comment by renekliment** [comment]
The old API is still supported.

**Comment by Bibelo** [comment]
Thank you for your answer!

I have no way of knowing what's wrong. I've run the script at least 15 times, with variations. I tried creating a new object. That was looong because the thing tries to compile and install *every single time*

**Comment by Bibelo** [comment]
Still no answer from the dev, while some users have managed to make it work without giving the solution.

"The old API is still supported" does not help me.

**Comment by s1h4d0w** [comment]
This does seem to be a problem on Amazon's end. I have the exact same issue, I just commented on an older issue: https://github.com/alexa-pi/AlexaPi/issues/208#issuecomment-368525636

Everything is set up as it should be on my side, but when trying to allow the app on the Amazon website it just gives the error OP posted.

**Comment by EmerickH** [comment]
Due to a large number of issues, this one is going to be closed because we think your problem is solved.
If you still have any problem, please feel free to re-open it!
