### ISSUE TITLE
Mic issue

### ISSUE THREAD

**Issue by seannervt** [alexa-pi/AlexaPi#369]
I've gone through all the Wiki's and debugging and cannot figure what's wrong. I either get an error saying the resource is busy or nothing at all when I try to test the mic.

**The debugging script**
http://www.alsa-project.org/db/?f=8386e3254f2355dbd1b3458b2a658624b6e03360

**Your OS (including version) where you are running AlexaPi:**
PRETTY_NAME="Raspbian GNU/Linux 8 (jessie)"
NAME="Raspbian GNU/Linux"
VERSION_ID="8"
VERSION="8 (jessie)"
ID=raspbian
ID_LIKE=debian

**Your hardware platform and model you are running on:**
Raspberry Pi 2

**Python release (python2 --version):**
Python 2.7.9 (default, Sep 17 2016, 20:26:04)

**Comment by EmerickH** [comment]
Hello,
This issue is quite old so I suppose you solved it or abandoned since.
If you still have the issue, please re-open this issue and provide your **config.yaml**

Emerick
