### ISSUE TITLE
How can i make Alexa to trigger/execute a script .sh file i have in my Pi with a custom trigger word please?

### ISSUE THREAD

**Issue by jabulonboaz** [alexa-pi/AlexaPi#378]
How can i make Alexa to trigger/execute a script .sh file i have in my Pi with a custom trigger word ?
E.g "Alexa trigger wifi on" and then a wifi_on.sh script is executed from within my Pi.
Or say “Alexa turn on projector” and then a script I have called say ‘projector_on.sh’ is executed in the Pi locally?

**Comment by jabulonboaz** [comment]
Anyone pls?

**Comment by renekliment** [comment]
Since this is pretty frequently asked, it's now in the F.A.Q.: https://github.com/alexa-pi/AlexaPi/wiki/Q&A-(FAQ)#how-do-i-run-a-local-command--script-when-i-say-x

**Comment by jabulonboaz** [comment]
@renekliment excuse my ignorance but that url you just posted points to an empty uncreated FAQ with no question or answer. Did i do something wrong?
Have you posted an answer somewhere?
Regards

**Comment by renekliment** [comment]
@jabulonboaz The link works. Make sure you click it so you don't miss something in the URL. You can also get there from local wiki. Post a screenshot if your issue persists.

**Comment by jabulonboaz** [comment]
@renekliment thank u i found it now but the answer is very disappointing as i lack the skills to do number 2 and even though i know how to write my own skill and have done so in the past to do option 1 that won't work for my original ask which is local integration as in everything is triggered from the Pi HW behind the same LAN.
