### ISSUE TITLE
Can we  change alexa-sample-app to use renderTemplate for the third party app?

### ISSUE THREAD

**Issue by Lpistos** [alexa-pi/AlexaPi#383]
Thank you for reporting an issue with **AlexaPi**.

Make sure you are running the latest version of **AlexaPi**, and look through [issues](https://github.com/alexa-pi/AlexaPi/issues?utf8=%E2%9C%93&q=is%3Aissue) before submitting.

Check out our [Wiki](https://github.com/alexa-pi/AlexaPi/wiki/), and make sure to look at [Debugging](https://github.com/alexa-pi/AlexaPi/wiki/Debugging/), and [Audio debugging](https://github.com/alexa-pi/AlexaPi/wiki/Audio-setup-&-debugging) in particular before filing an issue.

In order to help troubleshooting, be sure to include the following information:

**Output of the [audio debugging script](https://github.com/alexa-pi/AlexaPi/wiki/Audio-setup-&-debugging#audio-debugging-script).**

**Your OS (including version) where you are running AlexaPi:**
```
Windows 10
```

**Your hardware platform and model you are running on:**
```
desktop - intel i7  ram 16 etc

```

**Python release (`python2 --version`):**
``` 
python 3.6.4

```

**Description of problem:**
```
As we know the body template 1 works fine in Alexa sample app
however, custom skill for echo show which works fine in echo show doesn't work in the sample app


```

**Expected:**
```
if it is possible we want to change some setting in sample app to support the render template function
**you don't have to simply tell me that it's not supported by amazon. I already have searched a lot of documents I could find. so please tell me what is possible.** Thank you.
```

**Problem-relevant `config.yaml` entries:**
```

```

**Steps to reproduce:**

1. 
2. 
3. 

**Traceback (if applicable):**
```

```

**Additional info:**
```
![image](https://user-images.githubusercontent.com/30401692/37151622-93f29306-2319-11e8-9f33-6b0c69b42442.png)

```

**Comment by EmerickH** [comment]
First **THIS IS NOT "Alexa sample app"**,
This is AlexaPi, and this project uses an old version of Alexa API 1.0, that doesn't support new skills.
