### ISSUE TITLE
Failing on Install

### ISSUE THREAD

**Issue by gschwiter** [alexa-pi/AlexaPi#384]
Thank you for reporting an issue with **AlexaPi**.

Make sure you are running the latest version of **AlexaPi**, and look through [issues](https://github.com/alexa-pi/AlexaPi/issues?utf8=%E2%9C%93&q=is%3Aissue) before submitting.

Check out our [Wiki](https://github.com/alexa-pi/AlexaPi/wiki/), and make sure to look at [Debugging](https://github.com/alexa-pi/AlexaPi/wiki/Debugging/), and [Audio debugging](https://github.com/alexa-pi/AlexaPi/wiki/Audio-setup-&-debugging) in particular before filing an issue.

In order to help troubleshooting, be sure to include the following information:

**Output of the [audio debugging script](https://github.com/alexa-pi/AlexaPi/wiki/Audio-setup-&-debugging#audio-debugging-script).**

**Your OS (including version) where you are running AlexaPi:**
Linux Version 4.4.44-1-ARCH
HamVoip 1.5rc4-15 AllStar
Asterisk 1.4.23

**Your hardware platform and model you are running on:**
PI3

**Python release (`python2 --version`):**
I think the problem is here
python2-setuptools: /usr/bin/easy_install-2.7 exists in filesystem

**Description of problem:**
I am having an issue with the initial install, I believe its failing on the following.
error: failed to commit transaction (conflicting files)
python2-setuptools: /usr/bin/easy_install-2.7 exists in filesystem
Errors occurred, no packages were upgraded.
[root@node1 opt]#

**Additional info:**

Failing on Install
I am having an issue with the initial install, I believe its failing on the following.
error: failed to commit transaction (conflicting files)
python2-setuptools: /usr/bin/easy_install-2.7 exists in filesystem
Errors occurred, no packages were upgraded.
[root@node1 opt]#

I’m trying to run this on an existing build to integrate it into another project. Listed is the version of linux and other packages running on the PI3.
Linux Version 4.4.44-1-ARCH
HamVoip 1.5rc4-15 AllStar
Asterisk 1.4.23
I have listed the full setup errors. Any ides or direction would be great.
 root@node1 opt]# sudo pacman -Sy git
:: Synchronizing package databases...
 core is up to date
 extra is up to date
 community is up to date
 alarm is up to date
 aur is up to date
 hamvoip is up to date
warning: git-2.7.4-1 is up to date -- reinstalling
resolving dependencies...
looking for conflicting packages...

Packages (1) git-2.7.4-1

Total Download Size:    3.46 MiB
Total Installed Size:  23.56 MiB
Net Upgrade Size:       0.00 MiB

:: Proceed with installation? [Y/n] y
:: Retrieving packages...
 git-2.7.4-1-armv7h                    3.5 MiB  2.23M/s 00:02 [##################################] 100%
(1/1) checking keys in keyring                                [##################################] 100%
(1/1) checking package integrity                              [##################################] 100%
(1/1) loading package files                                   [##################################] 100%
(1/1) checking for file conflicts                             [##################################] 100%
(1/1) checking available disk space                           [##################################] 100%
:: Processing package changes...
(1/1) reinstalling git                                        [##################################] 100%
[root@node1 opt]# sudo git clone https://github.com/alexa-pi/AlexaPi.git
fatal: destination path 'AlexaPi' already exists and is not an empty directory.
[root@node1 opt]# sudo pacman -Sy git
:: Synchronizing package databases...
 core is up to date
 extra is up to date
 community is up to date
 alarm is up to date
 aur is up to date
 hamvoip is up to date
warning: git-2.7.4-1 is up to date -- reinstalling
resolving dependencies...
looking for conflicting packages...

Packages (1) git-2.7.4-1

Total Installed Size:  23.56 MiB
Net Upgrade Size:       0.00 MiB

:: Proceed with installation? [Y/n] y
(1/1) checking keys in keyring                                [##################################] 100%
(1/1) checking package integrity                              [##################################] 100%
(1/1) loading package files                                   [##################################] 100%
(1/1) checking for file conflicts                             [##################################] 100%
(1/1) checking available disk space                           [##################################] 100%
:: Processing package changes...
(1/1) reinstalling git                                        [##################################] 100%
[root@node1 opt]# sudo git clone https://github.com/alexa-pi/AlexaPi.git
Cloning into 'AlexaPi'...
remote: Counting objects: 945, done.
remote: Compressing objects: 100% (3/3), done.
remote: Total 945 (delta 0), reused 0 (delta 0), pack-reused 942
Receiving objects: 100% (945/945), 543.23 KiB | 816.00 KiB/s, done.
Resolving deltas: 100% (595/595), done.
Checking connectivity... done.
[root@node1 opt]# sudo ./AlexaPi/src/scripts/setup.sh
TIP: When there is a value in brackets like [default_value], hit Enter to use it.

Which operating system are you using?
         debian - Debian, Raspbian, Armbian, Ubuntu or other Debian-based
      archlinux - Arch Linux or Arch Linux-based
Your OS [debian]: archlinux
Which device are you using?
           chip - C.H.I.P.
       hyperion - Integrate with Hyperion Ambient Lightning Software
    magicmirror - Integrating with Magic Mirror project (MMM-AlexaPi)
       orangepi - Orange Pi or another H3 based board
          other - other SBCs, desktops, or anything else
    raspberrypi - all Raspberry Pi variants
         serial - an Arduino controled device for example; used for Teddy Ruxpin
Your device [raspberrypi]:
Do you want AlexaPi to run on boot?
You have these options:
0 - NO
1 - yes, use systemd (default, RECOMMENDED and awesome)
2 - yes, use a classic init script (for a very old PC or an embedded system)
Which option do you prefer? [1]: 1
Creating a user to run AlexaPi under ... user already exists. That's cool - using that.
gpio:x:1000:alexapi
audio:x:92:alexapi
Would you like to also install Airplay support (Y/n)? n
:: Synchronizing package databases...
 core is up to date
 extra is up to date
 community is up to date
 alarm is up to date
 aur is up to date
 hamvoip is up to date
:: There are 25 members in group base-devel:
:: Repository core
   1) autoconf  2) automake  3) binutils  4) bison  5) fakeroot  6) file  7) findutils  8) flex
   9) gawk  10) gcc  11) gettext  12) grep  13) groff  14) gzip  15) libtool  16) m4  17) make
   18) pacman  19) patch  20) pkg-config  21) sed  22) sudo  23) texinfo  24) util-linux  25) which

Enter a selection (default=all):
warning: autoconf-2.69-2 is up to date -- skipping
warning: automake-1.15-1 is up to date -- skipping
warning: binutils-2.26-3 is up to date -- skipping
warning: file-5.25-1 is up to date -- skipping
warning: findutils-4.6.0-1 is up to date -- skipping
warning: gawk-4.1.3-1 is up to date -- skipping
warning: gcc-5.3.0-5 is up to date -- skipping
warning: gettext-0.19.7-1 is up to date -- skipping
warning: grep-2.24-1 is up to date -- skipping
warning: groff-1.22.3-5 is up to date -- skipping
warning: gzip-1.6-1 is up to date -- skipping
warning: libtool-2.4.6-4 is up to date -- skipping
warning: m4-1.4.17-1 is up to date -- skipping
warning: make-4.1-3 is up to date -- skipping
warning: pacman-5.0.1-2.1 is up to date -- skipping
warning: sed-4.2.2-3 is up to date -- skipping
warning: sudo-1.8.15-1 is up to date -- skipping
warning: texinfo-6.1-1 is up to date -- skipping
warning: util-linux-2.27.1-1 is up to date -- skipping
warning: which-2.21-1 is up to date -- skipping
warning: git-2.7.4-1 is up to date -- skipping
warning: python2-2.7.11-2 is up to date -- skipping
warning: sox-14.4.2-1 is up to date -- skipping
warning: gcc-5.3.0-5 is up to date -- skipping
resolving dependencies...
:: There are 5 providers available for libgl:
:: Repository extra
   1) mesa-libgl
:: Repository alarm
   2) gpu-viv-bin-mx6q-dfb  3) gpu-viv-bin-mx6q-fb  4) gpu-viv-bin-mx6q-wl  5) gpu-viv-bin-mx6q-x11

Enter a number (default=1):
:: There are 2 providers available for libx264.so=148-32:
:: Repository extra
   1) libx264  2) libx264-10bit

Enter a number (default=1):
looking for conflicting packages...
warning: dependency cycle detected:
warning: harfbuzz will be installed before its freetype2 dependency

Packages (123) a52dec-0.7.4-8  cairo-1.14.6-1  damageproto-1.2.1-3  dcadec-0.2.0-1  faad2-2.7-4
               ffmpeg2.8-2.8.6-1  fixesproto-5.0-3  fontconfig-2.11.1-2  freetype2-2.6.3-1
               fribidi-0.19.7-1  giflib-5.1.2-1  graphite-1:1.3.6-1  harfbuzz-1.2.3-1
               hicolor-icon-theme-0.15-1  inputproto-2.3.1-1  jack-0.124.1-6  kbproto-1.0.7-1
               lcms2-2.7-1  libass-0.13.2-1  libasyncns-0.8-5  libbluray-0.9.2-1  libdatrie-0.2.10-1
               libdca-0.0.5-4  libdrm-2.4.67-1  libdvbpsi-1:1.3.0-1  libdvdnav-5.0.3-1
               libdvdread-5.0.4-1  libebml-1.3.3-2  libice-1.0.9-1  libjpeg-turbo-1.4.2-2
               libkate-0.4.1-5  libmatroska-1.4.4-1  libmng-2.0.3-1  libmodplug-0.8.8.5-2
               libmpcdec-1:0.1+r475-1  libmpeg2-0.5.1-5  libomxil-bellagio-0.9.3-1
               libpciaccess-0.13.4-1  libproxy-0.4.12-1  libshout-1:2.4.1-2  libsm-1.2.2-2
               libsoxr-0.1.2-1  libssh-0.7.3-1  libtar-1.2.20-2  libthai-0.1.24-1  libtheora-1.1.1-3
               libtiff-4.0.6-2  libtiger-0.3.4-4  libtxc_dxtn-1.0.1-6  libupnp-1.6.19-1  libva-1.6.2-1
               libvdpau-1.1.1-2  libvpx-1.5.0-4  libwebp-0.5.0-1  libx11-1.6.3-1
               libx264-2:148.20160103-1  libxau-1.0.8-2  libxcb-1.11.1-1  libxdamage-1.1.4-2
               libxdmcp-1.1.2-1  libxext-1.3.3-1  libxfixes-5.0.1-1  libxft-2.3.2-1  libxi-1.7.6-1
               libxinerama-1.1.3-2  libxmu-1.1.2-1  libxpm-3.5.11-1  libxrandr-1.5.0-1
               libxrender-0.9.9-1  libxshmfence-1.2-1  libxt-1.1.5-1  libxtst-1.2.2-1  libxv-1.0.10-1
               libxxf86vm-1.1.4-1  llvm-libs-3.7.1-1  mesa-11.1.2-1  mesa-libgl-11.1.2-1
               openjpeg-1.5.2-1  opus-1.2.1-1  orc-0.4.25-1  pango-1.39.0-1  pixman-0.34.0-1
               python2-packaging-16.5-1  python2-pyparsing-2.1.0-1  python2-setuptools-1:20.3.1-1
               python2-six-1.10.0-1  qt4-4.8.7-7  randrproto-1.5.0-1  recordproto-1.14.2-2
               renderproto-0.11.1-3  schroedinger-1.0.11-3  sdl-1.2.15-7  sdl_image-1.2.12-3
               taglib-1.10-3  v4l-utils-1.10.0-1  vid.stab-1.1-1  videoproto-2.3.3-1  wayland-1.10.0-1
               x265-1.9-1  xcb-proto-1.11-2  xcb-util-keysyms-0.4.0-1  xdg-utils-1.1.1-1
               xextproto-7.3.0-1  xf86vidmodeproto-2.3.1-3  xineramaproto-1.2.1-3  xorg-xset-1.2.3-1
               xproto-7.0.28-1  xvidcore-1.3.4-1  zita-alsa-pcmi-0.2.0-3  zita-resampler-1.3.0-5
               zvbi-0.2.35-1  bison-3.0.4-1  fakeroot-1.20.2-1  flex-2.6.0-2  libid3tag-0.15.1b-8
               libmad-0.15.1b-7  libpulse-8.0-3  patch-2.7.5-1  pkg-config-0.29.1-1
               portaudio-19_20140130-3  python2-pip-8.1.0-1  swig-3.0.8-1  vlc-2.2.2-3

Total Installed Size:  288.80 MiB

:: Proceed with installation? [Y/n]
(123/123) checking keys in keyring                            [##################################] 100%
(123/123) checking package integrity                          [##################################] 100%
(123/123) loading package files                               [##################################] 100%
(123/123) checking for file conflicts                         [##################################] 100%
error: failed to commit transaction (conflicting files)
python2-setuptools: /usr/bin/easy_install-2.7 exists in filesystem
Errors occurred, no packages were upgraded.
[root@node1 opt]# ^C
[root@node1 opt]#

[root@node1 opt]# sudo systemctl status AlexaPi.service
* AlexaPi.service - Alexa client for all your devices
   Loaded: loaded (/usr/lib/systemd/system/AlexaPi.service; enabled; vendor preset: disabled)
  Drop-In: /etc/systemd/system/AlexaPi.service.d
           `-usergroup-root.conf
   Active: failed (Result: exit-code) since Thu 2018-03-08 20:44:56 HST; 27s ago
     Docs: https://github.com/alexa-pi/AlexaPi/wiki
  Process: 1825 ExecStart=/usr/bin/python /opt/AlexaPi/src/main.py --daemon (code=exited, status=1/FAIL
 Main PID: 1825 (code=exited, status=1/FAILURE)

Mar 08 20:44:55 node1 systemd[1]: Started Alexa client for all your devices.
Mar 08 20:44:56 node1 python[1825]: Traceback (most recent call last):
Mar 08 20:44:56 node1 python[1825]:   File "/opt/AlexaPi/src/main.py", line 17, in <module>
Mar 08 20:44:56 node1 python[1825]:     from future.builtins import bytes
Mar 08 20:44:56 node1 python[1825]: ImportError: No module named 'future'
Mar 08 20:44:56 node1 systemd[1]: AlexaPi.service: Main process exited, code=exited, status=1/FAILURE
Mar 08 20:44:56 node1 systemd[1]: AlexaPi.service: Unit entered failed state.
Mar 08 20:44:56 node1 systemd[1]: AlexaPi.service: Failed with result 'exit-code'.

**Comment by maso27** [comment]
You could try running
`pacman -S --force python2 python2-pip`
before the install.

Once they're installed, it shouldn't try to install them again in the script.

I'm basing that on the suggestion [here](https://stackoverflow.com/questions/38286602/archlinux-pip-and-setuptools-not-upgraded), so proceed at your own risk.

**Comment by gschwiter** [comment]
[root@node1 opt]# sudo systemctl status AlexaPi.service
* AlexaPi.service - Alexa client for all your devices
   Loaded: loaded (/usr/lib/systemd/system/AlexaPi.service; enabled; vendor preset: disabled)
  Drop-In: /etc/systemd/system/AlexaPi.service.d
           `-force-python2.conf, usergroup-root.conf
   Active: active (running) since Fri 2018-03-09 21:35:32 HST; 2h 19min ago
     Docs: https://github.com/alexa-pi/AlexaPi/wiki
 Main PID: 369 (python2)
    Tasks: 3 (limit: 512)
   CGroup: /system.slice/AlexaPi.service
           `-369 /usr/bin/python2 /opt/AlexaPi/src/main.py --daemon

Mar 09 21:35:42 node1 python2[369]:   File "/usr/lib/python2.7/site-packages/pyaudio.py", line 441, in __init__
Mar 09 21:35:42 node1 python2[369]:     self._stream = pa.open(**arguments)
Mar 09 21:35:42 node1 python2[369]: IOError: [Errno -9996] Invalid input device (no default output device)
Mar 09 21:35:42 node1 python2[369]: ALSA lib pcm_dmix.c:1029:(snd_pcm_dmix_open) unable to open slave
Mar 09 21:35:42 node1 python2[369]: [73d00f00] alsa audio output error: cannot open ALSA device "default": Device or resource busy
Mar 09 21:35:42 node1 python2[369]: [73d00f00] core audio output error: Audio output failed
Mar 09 21:35:42 node1 python2[369]: [73d00f00] core audio output error: The audio device "default" could not be used:
Mar 09 21:35:42 node1 python2[369]: Device or resource busy.
Mar 09 21:35:42 node1 python2[369]: [73d00f00] core audio output error: module not functional
Mar 09 21:35:42 node1 python2[369]: [73924ab0] core decoder error: failed to create audio output

**Comment by EmerickH** [comment]
Hello,
you must setup your audio
List output devices with `arecord -L` and change it in the config with something like:
```
input_device = plughw:CARD=YOURCARD,DEV=0
```
(you may also have to do it with `output_device ` and `aplay -L`)

**Comment by EmerickH** [comment]
Due to a large number of issues, this one is going to be closed because we think your problem is solved.
If you still have any problem, please feel free to re-open it!
