### ISSUE TITLE
Reminders not working

### ISSUE THREAD

**Issue by jfreakazoid** [alexa-pi/AlexaPi#398]
Thank you for reporting an issue with **AlexaPi**.

Make sure you are running the latest version of **AlexaPi**, and look through [issues](https://github.com/alexa-pi/AlexaPi/issues?utf8=%E2%9C%93&q=is%3Aissue) before submitting.

Check out our [Wiki](https://github.com/alexa-pi/AlexaPi/wiki/), and make sure to look at [Debugging](https://github.com/alexa-pi/AlexaPi/wiki/Debugging/), and [Audio debugging](https://github.com/alexa-pi/AlexaPi/wiki/Audio-setup-&-debugging) in particular before filing an issue.

In order to help troubleshooting, be sure to include the following information:

**Output of the [audio debugging script](https://github.com/alexa-pi/AlexaPi/wiki/Audio-setup-&-debugging#audio-debugging-script).**

**Your OS (including version) where you are running AlexaPi:**
``` 
Raspbian Stretch
```

**Your hardware platform and model you are running on:**
``` 
Raspberry Pi 2
```

**Python release (`python2 --version`):**
```
2.7.13
```

**Description of problem:**
```
Dear Sir, first at all thank you very much for this flawless tutoriol, however despite that AlexaPi is running pretty well in my Rpi2, I have an issue that I’m not able to figure out related with setting timers, reminders or alarms. I already checked the settings in my amazon developer account and it’s ticked. Do you have any clue about where is the problem? Thank you in advance. Best regards,

```

**Expected:**
```

```

**Problem-relevant `config.yaml` entries:**
```

```

**Steps to reproduce:**

1. 
2. 
3. 

**Traceback (if applicable):**
```

```

**Additional info:**
```

```

**Comment by EmerickH** [comment]
See #391 and especially https://github.com/alexa-pi/AlexaPi/issues/391#issuecomment-406262747
