### ISSUE TITLE
How to force Alexa to talk to me in english ?

### ISSUE THREAD

**Issue by zdaar** [alexa-pi/AlexaPi#409]
Hello, 

I setup an AlexaPI and it is working fine.
However, she talks back to me in french and I do not want that. I'd like her to speak english.
How to force it ?

Thanks in advance

**Comment by EmerickH** [comment]
Très étrange! Il semblerait que Amazon ait intégré les autres langues à l'ancienne API? (normalement pas possible #328). Essayez de changer la langue dans les paramètres sur https://alexa.amazon.fr/

Very strange! It seems that Amazon has integrated other languages to the old API? (normally not possible #328). Try to change the language in the settings on https://alexa.amazon.fr/

**Comment by EmerickH** [comment]
@zdaar You don't replied so I suppose that your problem is fixed.
If you still have the issue, please re-open this issue and provide more information please.

Emerick
