### ISSUE TITLE
Getting Mic to Work 

### ISSUE THREAD

**Issue by ArthurBarker** [alexa-pi/AlexaPi#410]
Thank you for reporting an issue with **AlexaPi**.

Make sure you are running the latest version of **AlexaPi**, and look through [issues](https://github.com/alexa-pi/AlexaPi/issues?utf8=%E2%9C%93&q=is%3Aissue) before submitting.

Check out our [Wiki](https://github.com/alexa-pi/AlexaPi/wiki/), and make sure to look at [Debugging](https://github.com/alexa-pi/AlexaPi/wiki/Debugging/), and [Audio debugging](https://github.com/alexa-pi/AlexaPi/wiki/Audio-setup-&-debugging) in particular before filing an issue.

In order to help troubleshooting, be sure to include the following information:

**Output of the [audio debugging script](https://github.com/alexa-pi/AlexaPi/wiki/Audio-setup-&-debugging#audio-debugging-script).**

**Your OS (including version) where you are running AlexaPi:**
```Raspberry Pi
```

**Your hardware platform and model you are running on:**
```Raspberry Pi 3 b+

```

**Python release (`python2 --version`):**
```

```

**Description of problem:**
```I am trying to connect a mic to alexapi but it won't recongise it. I have tried with a differen't mic and it works fine but I am not using a smaller one which is my own and nothing is happening. It's a Lavalier Microphone "clip on microhpone". Is there anything I need to change? A detail description would be appricaited, I am new to all this. 

```

**Expected:**
```

```

**Problem-relevant `config.yaml` entries:**
```

```

**Steps to reproduce:**

1. 
2. 
3. 

**Traceback (if applicable):**
```

```

**Additional info:**
```

```

**Comment by EmerickH** [comment]
Hello,
Your issue is incomplete, please add more informations and then reopen it.
