### ISSUE TITLE
Issue with time and skill set

### ISSUE THREAD

**Issue by mschindl** [alexa-pi/AlexaPi#428]
Hi,
Is it possible that Alexa uses the **right time**? If yes, where can I change it? My current time is -1 hour.
And, can I use a **custom skill** set? For example: https://www.amazon.de/gp/product/B01NBHJZII
Thank you

**Comment by EmerickH** [comment]
Hello,
Try to change settings in: https://alexa.amazon.com/
For the time I'm sure you can change it, for skills, some are working, others not, you have to try
