### ISSUE TITLE
CLIENT NOT CONNECTED

### ISSUE THREAD

**Issue by iotMice** [alexa-pi/AlexaPi#434]
I am trying to install alexa c++ sdk for raspberrypi  model 3B+ (Stretch installed in it).
I followed the steps given in the tutorial.
My device is getting authorized as well,
after authorization it shows "client not connected"
and then it shows "alexa is in idle state".

How to solve client not connected issue.
I have downloaded config.json  from OTHER DEVICES AND PLATFORM tab in developer account of alexa.
config.json has client id , and product name.

how to solve the problem

**Comment by renekliment** [comment]
Incorrect repo (this is an independent Python project). Sorry for the naming confusion.
