### ISSUE TITLE
Install fails on missing vlc-nox

### ISSUE THREAD

**Issue by thomasthomas11235** [alexa-pi/AlexaPi#436]
Ubuntu 18.04
Intel i5 PC
Python 2.7
**Description of problem:**
Install fails while trying to install vlc-nox. vlc-nox is now contained in vlc-bin

**Steps to reproduce:**
1. Run setup script on ubuntu 18.04

**Comment by EmerickH** [comment]
Hello,
I can't find this information somewhere else on internet, but maybe...
Try to edit this file:
```
AlexaPi/src/scripts/inc/os/debian.sh
```
and replace `vlc-nox` with `vlc-bin`

**Comment by belfasti** [comment]
How to edit debian.sh  on raspberry pi

**Comment by belfasti** [comment]
it does not allow me to change debian.sh on raspberry pi

**Comment by renekliment** [comment]
It should be fixed now. If you could check with a clean install that would be awesome.
