### ISSUE TITLE
Timers and Alarms not functional 

### ISSUE THREAD

**Issue by Ssabaker** [alexa-pi/AlexaPi#446]
**Your OS (including version) where you are running AlexaPi:**
_Note: Raspbian older than Stretch is not supported!_
```
2018-11-13-raspbian-stretch-full
```

**Your hardware platform and model you are running on:**
```
RPi 3b+
```

**Description of problem:**
```
Alexa will accept command for timer but it will never go off.  
However for setting alarms; states that there is a problem and that the alarm could not be set.  
The clock works fine and will report the correct time when prompted.

```

**Comment by renekliment** [comment]
https://github.com/alexa-pi/AlexaPi/wiki/Q&A-(FAQ)#why-do-i-see-the-alexapi-device-offline-in-the-alexa-app--why-do-i-get-timers-and-alarms-are-not-currently-supported-on-this-device
