### ISSUE TITLE
install fails on missing vlc-nox

### ISSUE THREAD

**Issue by thambu1710** [alexa-pi/AlexaPi#467]
i am runing raspberry pi latest version 
i need help today its urgent 
pls improve the setup.sh code

**Comment by erikhermesman** [comment]
Edit this file:

AlexaPi/src/scripts/inc/os/debian.sh

and replace vlc-nox with vlc-bin

The source of this information came from [https://github.com/alexa-pi/AlexaPi/issues/436](https://github.com/alexa-pi/AlexaPi/issues/436)

**Comment by EmerickH** [comment]
Duplicate of #436
