### ISSUE TITLE
How to link my google calendar to my AlexaPi

### ISSUE THREAD

**Issue by GlitchedVortex** [alexa-pi/AlexaPi#494]
Thank you for reporting an issue with **AlexaPi**.

Make sure you are running the latest version of **AlexaPi**, and look through [issues](https://github.com/alexa-pi/AlexaPi/issues?utf8=%E2%9C%93&q=is%3Aissue) before submitting.

Check out our [Wiki](https://github.com/alexa-pi/AlexaPi/wiki/), and make sure to look at [Debugging](https://github.com/alexa-pi/AlexaPi/wiki/Debugging/), and [Audio debugging](https://github.com/alexa-pi/AlexaPi/wiki/Audio-setup-&-debugging) in particular before filing an issue.

In order to help troubleshooting, be sure to include the following information:

**Output of the [audio debugging script](https://github.com/alexa-pi/AlexaPi/wiki/Audio-setup-&-debugging#audio-debugging-script).**

**Your OS (including version) where you are running AlexaPi:**
_Note: Raspbian older than Stretch is not supported!_
```
Rasbian Buster
```

**Your hardware platform and model you are running on:**
```
Raspberry Pi Model B
```

**Python release (`python3 --version`):**
```
Python 3.7.3
```

**Description of problem:**
```
I wish to link my google calendar with Alexapi but when asking to add an event it tells me there is no calendar associated with it
```

**Expected:**
```
Alexa to be linked with my google calendar
```

**Problem-relevant `config.yaml` entries:**
```

```

**Steps to reproduce:**

1. 
2. 
3. 

**Traceback (if applicable):**
```

```

**Additional info:**
```
I have followed the guide for this AlexaPi
https://github.com/alexa-pi/AlexaPi
and then also using MMM-AlexaPi as part of it interacting with my MagicMirror project which is what AlexaPi is being used for
https://github.com/dgonano/MMM-AlexaPi

As far as i can tell, Alexa is working as it should by answering basic questions like `what time is it?` etc but doesn't currently link to my calendar.

I think i have provided all the relevant information. If there is anything else required that i have missed please let me know
```

**Comment by lordjoo** [comment]
Did you find a  way to do this
