### ISSUE TITLE
Alexa gets messed up after Ctrl-C during playback

### ISSUE THREAD

**Issue by GadgetReactor** [alexa-pi/AlexaPi#56]
When playing back Tunein radio channels, I am not able to issue the Ctrl-C command. It also breaks voice detection thereafter.  Requires a Ctrl-Z and a kill -9. 

```
Sending Playback Progress Report Request...
Playback Progress Report was Successful!
```

**Comment by renekliment** [comment]
I can confirm this.

Normal voice triggering works for me when just playing TuneIn streams. It can be sometimes tricky to activate Alexa, because the music produces noise for the trigger word detection.
