### ISSUE TITLE
Crash: alsaaudio..Device or resource busy [plughw:1]

### ISSUE THREAD

**Issue by irthomasthomas** [alexa-pi/AlexaPi#58]
Just tried the latest version on a pc running ubuntu 14.04. It says hello before exiting with the following message:
line 498..    inp = alsaaudio.PCM(alsaaudio.PCM_CAPTURE, alsaaudio.PCM_NORMAL, config['sound']['device'])
alsaaudio.ALSAAudioError: Device or resource busy [plughw:1]

**Comment by irthomasthomas** [comment]
Thanks, I am running this in a terminal already. Am I supposed to configure the audio stream somewhere?

**Comment by CEOGavin** [comment]
`sudo nano /etc/opt/AlexaPi/config.yaml`

**Comment by ridai260** [comment]
Is it possible to simply use the inbuilt RPi3 audio jack for this? I've uninstalled pulse as it's causing nothing but issues, and when I run arecord -L, I only get 'null' or 'pulse'.

**Comment by irthomasthomas** [comment]
ok I set it to "default" and it works nicely now. Cheers.
