### ISSUE TITLE
Refactor: Setup script

### ISSUE THREAD

**Issue by renekliment** [alexa-pi/AlexaPi#60]
- Write it to be very modular.
- Do it is as platform-independent as possible.
- It will have to implement some checks - or should we ask the user about everything?
- In python? Maybe in a later phase if it makes sense?
- Needs to setup OS platforms (covers requirements install for major systems)
  - try to do as much we can via `pip`
  - apt-get based systems
  - pacman/yaourt based systems
  - yum (or whatever Fedora uses) based systems
  - Mason wrote a pretty comprehensive manual for Arch on RPi: [Arch setup](https://github.com/alexa-pi/AlexaPi/pull/28#issuecomment-251578831) and [making it work under the alexapi user](https://github.com/alexa-pi/AlexaPi/pull/28#issuecomment-253115465)
- Needs to also setup device platforms.
  - Don't forget to do the install of GPIO libraries for RPi and OrangePi
  - Apart from the RPi udev/permissions stuff on Arch, we'll have to do a similar thing for general sysfs gpio platforms (#37)

**Comment by renekliment** [comment]
I have to say, this is gonna be one of the less fun refactors. But what the hell, we can probably just put everything into functions, maybe separate files if it makes sense and ask the users what they want (which OS and device platforms) and call the corresponding functions and we're done super quick.

**Comment by illperipherals** [comment]
I vote for keeping this as shell script for the time being. I think it might be beneficial to start working our scripts towards a common skeleton (cli params, colors, logging) for consistency.
