### ISSUE TITLE
Python 3 support

### ISSUE THREAD

**Issue by renekliment** [alexa-pi/AlexaPi#7]
There are two sides of this:
- [x] a support to run in under py3
- [x] make py3 _selectable_ & probably default

We need to be sure that there is no major drop in performance there to use it as default.

~~Also, we need to be sure that all the dependencies support this to do that. If they don't - find another solution if possible. The base should however support py3 without a problem - achieve this first.~~ 
Everything works in Python 3 except for the CHIP_IO library.

**Comment by sammachin** [comment]
I think this may be a requirement for the new API, IIRC the python HTTP/2 lib that I was looking at only runs under Py3.

**Comment by renekliment** [comment]
If you mean [hyper](https://hyper.readthedocs.io/en/latest/) it should run under both py2 and py3.

> `hyper` supports Python 3.4 and Python 2.7.9, and can speak HTTP/2 and HTTP/1.1.

**Comment by renekliment** [comment]
Don't forget to enable Python 3 on Travis CI when this is done.
