### ISSUE TITLE
Do logging properly

### ISSUE THREAD

**Issue by renekliment** [alexa-pi/AlexaPi#75]
Probably use https://docs.python.org/2/library/logging.html
As @lechat mentioned in #67.

I'd personally like it if we could also have colors with this new thing.

**Comment by lechat** [comment]
The colors are possible. There is a couple of libs that will do that, but it can be done w/o them as well.

**Comment by renekliment** [comment]
Dope!

**Comment by renekliment** [comment]
Also, this should get rid of the stupid `tunein.log` file.

**Comment by renekliment** [comment]
Also, sometimes I've written `config['debug']` which wasn't just a trick to pass the value of debug into modules. There should be a config option (defaults to false, or like a zero logging level) for this and the command line parameter would override it. This could be useful for setting debug level even for when AlexaPi runs as daemon.

**Comment by lechat** [comment]
I find it harder to support if default logging is set to absolute silence. Default should be minimal logging stating that all started up and all is fine.

**Comment by renekliment** [comment]
Ah, you are right as usual :smiley_cat: 

Another thought: when running under systemd, don't output times as journal should do that.
