### ISSUE TITLE
500 :Internal Server Error

### ISSUE THREAD

**Issue by Karansheth** [alexa-pi/AlexaPi#83]
After Posting my issue with Pulse audio , Today i decided to start over again but while setting up during the auth process i am get the 500 server error, is this due to any changes on git ??
whats is the solution??

http://192.168.1.142:5050/code?error_description=An+unknown+scope+was+requested&error=invalid_scope

"500 Internal Server Error

The server encountered an unexpected condition which prevented it from fulfilling the request.

Powered by CherryPy 8.1.2"

**Comment by renekliment** [comment]
Damn, forgot to tag in commit message again! Ughhhh ... Fixed by #84.
