### ISSUE TITLE
How to reset the "automatic restart" option?

### ISSUE THREAD

**Issue by SneakyDave** [alexa-pi/AlexaPi#88]
I originally setup AlexaPi to restart on crashes, now realize that isn't such a good idea while debugging some errors, but after going back into startup, and re-configuring it to NOT restart on crashes, it still does. I couldn't find this option in config.yaml, so I'm curious if this is a system setting whereby I can shut it off?

**Comment by renekliment** [comment]
It's [hidden in the wiki](https://github.com/alexa-pi/AlexaPi/wiki/Code-notes#alexapi-restart-on-crashes) :-)
